local
_={_="gAC_AimbotDetected",a="Meth_Silent_Last",b="Meth_Silent_MX_Last",c="Meth_Silent_MY_Last",d="Meth_Silent_Threshold"}if!gAC.config.ANTI_METH
then
return
end
local
a,b,c,d,e=CurTime,IsValid,hook.Add,math.abs,{["weapon_physgun"]=!!1,["gmod_tool"]=!!1,["weapon_physcannon"]=!!1,["gmod_camera"]=!!1}local
function
a(a)return
a-(a%1)end
local
function
f(b,c)local
d=10^c||0
return
a(b*d+.5)/d
end
local
function
a(a,b)a.p=f(a.p,b)a.y=f(a.y,b)a.r=f(a.r,b)return
a
end
c("StartCommand","gAC.MethSilent",function(c,f)if
c:InVehicle()||c[_._]||!c:Alive()||c:GetObserverMode()~=OBS_MODE_NONE||c:IsBot()||!b(c)||c:IsTimingOut()||c:PacketLoss()>80
then
return
end
if
b(c:GetActiveWeapon())&&e[c:GetActiveWeapon():GetClass()]then
return
end
local
g=f:GetViewAngles()local
h,i,j,k,l=g.p,g.y,g.r,d(f:GetMouseX()),d(f:GetMouseY())if!c[_.a]then
c[_.a]=g
c[_.b]=k
c[_.c]=l
c[_.d]=0
return
end
local
f,h=a(c[_.a]),a(g)if
k>0&&l>0&&a(f,2)==a(h,2)then
if
c[_.d]>5
then
c[_._]=!!1
gAC.AddDetection(c,"Meth Silent-Aim Detected [Code 115]",gAC.config.METH_PUNISHMENT,gAC.config.METH_BANTIME)return
else
c[_.d]=c[_.d]+1
end
elseif
c[_.d]>0
then
c[_.d]=c[_.d]-1
end
c[_.a]=g
c[_.b]=k
c[_.c]=l
end)