local a = {a='p',b='y',c='r',d='Meth_Silent_Last',e='Meth_Silent_Threshold',f='gAC_AimbotDetected',g='config',h='Meth_Silent_MX_Last',i='Meth_Silent_MY_Last'}if!gAC[a.g].ANTI_METH
then
return
end
local
b=CurTime
local
c=IsValid
local
d=hook.Add
local
e=math.abs
local
f={["weapon_physgun"]=true,["gmod_tool"]=true,["weapon_physcannon"]=true,["gmod_camera"]=true}local
function
g(j)return
j-(j%1)end
local
function
h(j,k)local
l=10^(k
or
0)return
g(j*l+.5)/l
end
local
function
i(j,k)j[a.a]=h(j[a.a],k)j[a.b]=h(j[a.b],k)j[a.c]=h(j[a.c],k)return
j
end
d("StartCommand","Bad",function(j,k)if(j:InVehicle()||j[a.f]||!j:Alive()||j:GetObserverMode()!=OBS_MODE_NONE||j:IsBot()||!c(j)||j:IsTimingOut()||j:PacketLoss()>80)then
return
end
if
c(j:GetActiveWeapon())&&f[j:GetActiveWeapon():GetClass()]then
return
end
local
l=k:GetViewAngles()local
m,n,o=l[a.a],l[a.b],l[a.c]local
p=e(k:GetMouseX())local
q=e(k:GetMouseY())if!j[a.d]then
j[a.d]=l
j[a.h]=p
j[a.i]=q
j[a.e]=0
return
end
local
r,s=i(j[a.d]),i(l)if
p>0
and
q>0
and
i(r,2)==i(s,2)then
if
j[a.e]>5
then
j[a.f]=true
gAC.AddDetection(j,"Meth Silent-Aim Detected [Code 115]",gAC[a.g].METH_PUNISHMENT,gAC[a.g].METH_BANTIME)return
else
j[a.e]=j[a.e]+1
end
elseif
j[a.e]>0
then
j[a.e]=j[a.e]-1
end
j[a.d]=l
j[a.h]=p
j[a.i]=q
end)