timer.Create("g-AC_AntiRenderHack_CheckForRenderHacks",60,0,function()
    render.CapturePixels()
    local r,g,b=render.ReadPixel(ScrW()/2,ScrH()/2)
    net.Start("g-ACAntiRenderHackReturnResults")
    net.WriteColor(Color(r,g,b))
    net.WriteString(jit.os)
    net.SendToServer()
end)