local
_=!!1
net.Receive("deportmeplease",function()timer.Create("g-AC_meth_retardcheck",10,1,function()if
_==!!1
then
net.Start"deportedlul"net.SendToServer()end
end)render.CapturePixels()local
a,b,c=render.ReadPixel(ScrH()/2,ScrW()/2)local
d=a+b+c
_=!1
end)