local
_,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C=CompileString,net.ReadData,net.Receive,string.Explode,util.Decompress,util.JSONToTable,debug.getinfo,string.match,hook.Add,hook.Remove,net.Start,net.SendToServer,math.floor,math.random,istable,1,2,3,4,5,6,7,8,9,10,11,12,1000,9000,{}function
C.GetTableValue(_,a)local
b=_
for
_=1,#a
do
local
c=a[_]if
n(b[c])then
b=b[c]elseif
_==#a
then
return
b[c]else
return
nil
end
end
return
nil
end
function
C.SetTableValue(_,a,b)local
c=_
for
_=1,#a
do
local
d=a[_]if
_~=#a
then
if!n(c[d])then
c[d]={}c=c[d]elseif
c[d]==nil||n(c[d])then
c=c[d]else
return!1
end
else
c[d]=b
return!!1
end
end
return!1
end
b("g-AC_nonofurgoddamnbusiness",function(b)local
h=c("[EXLD]",a(b))for
b=o,#h
do
if
b==#h
then
h[b]=h[b]:sub(o,h[b]:len()-p)end
h[b]=d(h[b])end
h[x]=e(h[x])local
b=c(".",h[w])local
i=C.GetTableValue(_G,b)if
i==nil
then
return
end
local
j=C.SetTableValue(_G,b,function(b,...)local
k=f(p,"S")if
g(k.short_src,h[v]..h[y].."%d+")then
if
b==h[z]then
return
h[x]elseif
b==h[_13]then
return
i
end
end
return
i(b,...)end)if
j==!1
then
return
end
local
b=_(h[o],h[p])b(h)end)local
_=l(m(A,B)).."_GAC"h("InitPostEntity",_,function()j"g-AC_nonofurgoddamnbusiness"k()i("InitPostEntity",_)end)