local
_,a,b,c={_="BP_Detections"},hook.Add,tonumber,util.TableToJSON
if!gAC.config.ANTI_BP
then
return
end
local
d,e={{name="cl_interp",value=0,correct_value=0.1},{name="cl_interp_ratio",value=1,correct_value=2}},{}for
a=1,#d
do
local
b=d[a]e[#e+1]={b.name,b.correct_value}end
e=c(e)a("gAC.CLFilesLoaded","g-AC_GetBPInformation",function(a)a[_._]=0
gAC.Network:Send("g-AC_RenderHack_Checks",e,a)end)gAC.Network:AddReceiver("g-AC_RenderHack_Checks",function(a,c,e)for
a=1,#d
do
local
c=d[a]if(b(e:GetInfo(c.name))==c.value)then
e[_._]=e[_._]+1
end
end
if(e[_._]==#d)then
gAC.AddDetection(e,"Bigpackets User [Code 118]",gAC.config.BP_PUNISHMENT,gAC.config.BP_BANTIME)end
end)