local
_,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a_,aa,ab,ac,ad,ae,af,ag,ah,ai,aj,ak,al,am,an={_="stringrandom",a="ToSend",b="source",c="short_src",d="funcname",e="execidentifier",f="BCJitFuncs",g="dirtosvlua",h="SendBuffer",i="CompileData",j="RunString",k="CreateIdentifier",l="RunStringEx",m="CompileString",n="_VMEVENTS",o="gAC_Send"},debug.getinfo,debug.getregistry,jit.util.funcinfo,jit.util.funcbc,jit.attach,tostring,istable,math.random,bit.rol,util.TableToJSON,bit.band,bit.rshift,string.char,string.gsub,string.sub,timer.Simple,tonumber,isfunction,table.concat,net.ReadData,net.Receive,string.Explode,table.remove,util.CRC,math.ceil,util.Compress,util.Decompress,util.JSONToTable,string.match,net.Start,net.SendToServer,net.WriteUInt,net.WriteData,CompileString,hook.Add,hook.Remove,engine.TickInterval,0,1,2,3,4,5,6,7,8,9,10,11,12,13,1000,9000,.5,97,65,49,122,90,57,26,15,32,16,30,24,500
local
function
o(a)return
a-(a%M)end
local
function
p(a,b)local
c=L
for
d=L,31
do
local
e=(a*aa)+(b*aa)if
e~=o(e)then
c=c+N^d
end
a=o(a*aa)b=o(b*aa)end
return
c
end
local
y,S={OrigFuncs={},OrigNames={},ToSend={},AntiLua=!!1},M/K()function
y._D(a,b,c)c=c||""y.OrigFuncs[b]=a
y.OrigNames[b]=c
return
b
end
function
y.hs(a)local
b=#a
for
c=M,#a
do
b=p(b,i(b,R)+a:byte(c))end
return
i(b,O)end
function
y.dirtosvlua(a)local
b=a
b=v("/",b)if
b[1]=="addons"then
w(b,1)w(b,1)w(b,1)a=s(b,"/")elseif
b[1]=="lua"then
w(b,1)a=s(b,"/")elseif
b[1]=="gamemodes"then
w(b,1)a=s(b,"/")end
return
a
end
function
y.stringrandom(a)local
b=""for
a=M,a
do
local
a=o(h(M,P)+aa)if
a==M
then
b=b..m(h(ab,ae))elseif
a==N
then
b=b..m(h(ac,af))elseif
a==O
then
b=b..m(h(ad,ag))end
end
return
b
end
local
i=m(V)..y[_._](o(h(X,aj)+aa))function
y.GetTableValue(a,b)local
c=a
for
a=M,#b
do
local
d=b[a]if
g(c[d])then
c=c[d]elseif
a==#b
then
return
c[d]else
return
nil
end
end
return
nil
end
function
y.SetTableValue(a,b,c)local
d=a
for
a=M,#b
do
local
e=b[a]if
a~=#b
then
if
d[e]==nil
then
d[e]={}d=d[e]elseif
g(d[e])then
d=d[e]else
return!1
end
else
d[e]=c
return!!1
end
end
return!1
end
function
y.SendBuffer(a)if!y.AntiLua
then
return
end
local
b=#y[_.a]if
b<M
then
y[_.a][M]={[M]=a}elseif!y[_.a][b]then
y[_.a][b]={[M]=a}elseif#y[_.a][b]>=an
then
y[_.a][b+M]={[M]=a}else
y[_.a][b][#y[_.a][b]+M]=a
end
end
function
y.CompileData(a)return{func=a.func,source=a[_.b],short_src=a[_.c],what=a.what,lastlinedefined=a.lastlinedefined,linedefined=a.linedefined,funcname=a[_.d],code=a.code,proto=a.proto,execidentifier=a[_.e]}end
local
g,p={[0x46]=0x51,[0x47]=0x51,[0x48]=0x51,[0x49]=0x49,[0x4A]=0x49,[0x4B]=0x4B,[0x4C]=0x4B,[0x4D]=0x4B,[0x4E]=0x4E,[0x4F]=0x4E,[0x50]=0x4E,[0x51]=0x51,[0x52]=0x51,[0x53]=0x51},{[0x44]=0x54,[0x42]=0x41}local
function
K(a,b)local
c={}for
b=M,b.bytecodes-M
do
local
e=d(a,b)local
b=k(e,0xFF)if
g[b]then
e=g[b]end
if
p[b]then
e=e-b
e=e+p[b]end
c[#c+M]=m(k(e,0xFF),k(l(e,8),0xFF),k(l(e,16),0xFF),k(l(e,24),0xFF))end
return
q(x(s(c)))end
y[_.f]={}local
function
d(...)if
y[_.f]['bc']then
y[_.f]['bc'](...)end
end
y.LuaVM=function(a,...)local
b=c(a)b[_.b]=n(b[_.b],"^@","")if
b[_.b]==i
then
return
d(a,...)end
b[_.b]=y[_.g](b[_.b])b.proto=K(a,b)y[_.h](y[_.i](b))d(a,...)end
local
c={{{"hook","Add"},"hook.Add"},{{"hook","Remove"},"hook.Remove"},{{"hook","GetTable"},"hook.GetTable"},{{"surface","CreateFont"},"surface.CreateFont"},{{"concommand","Add"},"concommand.Add"},{{"AddConsoleCommand"},"AddConsoleCommand"}}for
b=M,#c
do
local
d=c[b]local
b=y.GetTableValue(_G,d[M])if
b==nil
then
continue
end
local
e=y._D(b,function(...)local
g=a(N,"fS")g[_.d]=d[N]g.func=f(g.func)g[_.b]=n(g[_.b],"^@","")g[_.b]=y[_.g](g[_.b])y[_.h](y[_.i](g))return
b(...)end,funcname)y.SetTableValue(_G,d[M],e)end
local
c,d=0,{}function
y.CreateIdentifier(a,b)if
a
then
if
d[a]then
c=c+1
a=a..c
end
else
a=b
if
d[a]then
c=c+1
a=b..c
end
end
d[a]=!!1
return
a
end
local
c=_G[_.j]_G[_.j]=y._D(_G[_.j],function(b,c,...)local
d,e=H(b,i,!1)if!d&&e
then
return
e
end
c=y[_.k](c,"RunString")local
e=a(N,"fS")e[_.d]="RunString"e.func=f(e.func)e[_.e]=c
e.code=b
e[_.b]=n(e[_.b],"^@","")e[_.b]=y[_.g](e[_.b])y[_.h](y[_.i](e))d=H(b,c)return
d()end,"RunString")local
c=_G[_.l]_G[_.l]=y._D(_G[_.l],function(b,c,...)local
d,e=H(b,i,!1)if!d&&e
then
return
e
end
c=y[_.k](c,"RunStringEx")local
e=a(N,"fS")e[_.d]="RunStringEx"e.func=f(e.func)e[_.e]=c
e.code=b
e[_.b]=n(e[_.b],"^@","")e[_.b]=y[_.g](e[_.b])y[_.h](y[_.i](e))d=H(b,c)return
d()end,"RunStringEx")_G[_.m]=y._D(_G[_.m],function(b,c,d,...)local
e,g=H(b,i,!1)if!e&&g
then
return
nil,g
end
c=y[_.k](c,"CompileString")local
e=a(N,"fS")e[_.d]="CompileString"e.func=f(e.func)e[_.e]=c
e.code=b
e[_.b]=n(e[_.b],"^@","")e[_.b]=y[_.g](e[_.b])y[_.h](y[_.i](e))return
H(b,c,d)end,"CompileString")local
c,d,f,g=_G[_.m],_G[_.j],y.hs'bc',b()g[_.n]=g[_.n]||{}g[_.n][f]=y.LuaVM
e(function()end,"")jit.attach=y._D(e,function(a,b,...)if
b=='bc'&&r(a)then
y[_.f]['bc']=a
return
end
return
e(a,b,...)end,"jit.attach")local
b,e=y[_._](o(h(X,ah)+aa)),V*S
local
i=e-M
I("Tick",b,function()if
g[_.n][f]~=y.LuaVM
then
g[_.n][f]=y.LuaVM
end
if
y[_.o]&&i>e
then
y.AntiLua=gAC.config.AntiLua_CHECK
if
y.AntiLua
then
local
a=y[_.a][M]if
a
then
y[_.o]("g-AC_LuaExec",j(a))w(y[_.a],M)else
y[_.o]("g-AC_LuaExec","1")end
end
i=L
end
i=i+M
end)u("g-AC_nonofurgoddamnbusiness",function(b)local
e=v("[EXLD]",t(b))for
b=M,#e
do
if
b==#e
then
e[b]=e[b]:sub(M,e[b]:len()-N)end
e[b]=A(e[b])end
e[V]=B(e[V])local
b=v(".",e[U])local
f=y.GetTableValue(_G,b)if
f==nil
then
return
end
local
g=y.SetTableValue(_G,b,function(b,...)local
h=a(N,"S")if
C(h[_.c],e[T]..e[W].."%d+")==h[_.c]then
if
b==e[X]then
return
e[V]elseif
b==e[Y]then
return
f
end
end
return
f(b,...)end)if
g==!1
then
return
end
y[_.o]=function(b,f)f=z(f)D(e[O])F(q(x(b..e[Q])),aj)G(f,#f)E()end
local
b=c(e[M],e[N])b(e,c,d)end)local
a=y[_._](o(h(X,ah)+aa))I("InitPostEntity",a,function()D"g-AC_nonofurgoddamnbusiness"E()J("InitPostEntity",a)end)