local
_,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a_,aa,ab,ac,ad,ae,af,ag,ah,ai,aj,ak,al,am={_="stringrandom",a="ToSend",b="source",c="short_src",d="funcname",e="execidentifier",f="dirtosvlua",g="SendBuffer",h="CompileData",i="RunString",j="CreateIdentifier",k="RunStringEx",l="CompileString",m="_VMEVENTS",n="gAC_Send"},debug.getinfo,debug.getregistry,jit.util.funcinfo,jit.util.funcbc,jit.attach,tostring,istable,math.random,bit.rol,util.TableToJSON,bit.band,bit.rshift,string.char,string.gsub,string.sub,timer.Simple,tonumber,table.concat,net.ReadData,net.Receive,string.Explode,table.remove,util.CRC,math.ceil,util.Compress,util.Decompress,util.JSONToTable,string.match,net.Start,net.SendToServer,net.WriteUInt,net.WriteData,CompileString,hook.Add,hook.Remove,engine.TickInterval,0,1,2,3,4,5,6,7,8,9,10,11,12,13,1000,9000,.5,97,65,49,122,90,57,26,15,32,16,30,24,500
local
function
o(a)return
a-(a%L)end
local
function
p(a,b)local
c=K
for
d=K,31
do
local
e=(a*a_)+(b*a_)if
e~=o(e)then
c=c+M^d
end
a=o(a*a_)b=o(b*a_)end
return
c
end
local
x,R={OrigFuncs={},OrigNames={},ToSend={},AntiLua=!!1},L/J()function
x._D(a,b,c)c=c||""x.OrigFuncs[b]=a
x.OrigNames[b]=c
return
b
end
function
x.hs(a)local
b=#a
for
c=L,#a
do
b=p(b,i(b,Q)+a:byte(c))end
return
i(b,N)end
function
x.dirtosvlua(a)local
b=a
b=u("/",b)if
b[1]=="addons"then
v(b,1)v(b,1)v(b,1)a=r(b,"/")elseif
b[1]=="lua"then
v(b,1)a=r(b,"/")elseif
b[1]=="gamemodes"then
v(b,1)a=r(b,"/")end
return
a
end
function
x.stringrandom(a)local
b=""for
a=L,a
do
local
a=o(h(L,O)+a_)if
a==L
then
b=b..m(h(aa,ad))elseif
a==M
then
b=b..m(h(ab,ae))elseif
a==N
then
b=b..m(h(ac,af))end
end
return
b
end
local
i=m(U)..x[_._](o(h(W,ai)+a_))function
x.GetTableValue(a,b)local
c=a
for
a=L,#b
do
local
d=b[a]if
g(c[d])then
c=c[d]elseif
a==#b
then
return
c[d]else
return
nil
end
end
return
nil
end
function
x.SetTableValue(a,b,c)local
d=a
for
a=L,#b
do
local
e=b[a]if
a~=#b
then
if
d[e]==nil
then
d[e]={}d=d[e]elseif
g(d[e])then
d=d[e]else
return!1
end
else
d[e]=c
return!!1
end
end
return!1
end
function
x.SendBuffer(a)if!x.AntiLua
then
return
end
local
b=#x[_.a]if
b<L
then
x[_.a][L]={[L]=a}elseif!x[_.a][b]then
x[_.a][b]={[L]=a}elseif#x[_.a][b]>=am
then
x[_.a][b+L]={[L]=a}else
x[_.a][b][#x[_.a][b]+L]=a
end
end
function
x.CompileData(a)return{func=a.func,source=a[_.b],short_src=a[_.c],what=a.what,lastlinedefined=a.lastlinedefined,linedefined=a.linedefined,funcname=a[_.d],code=a.code,proto=a.proto,execidentifier=a[_.e]}end
local
g,p={[0x46]=0x51,[0x47]=0x51,[0x48]=0x51,[0x49]=0x49,[0x4A]=0x49,[0x4B]=0x4B,[0x4C]=0x4B,[0x4D]=0x4B,[0x4E]=0x4E,[0x4F]=0x4E,[0x50]=0x4E,[0x51]=0x51,[0x52]=0x51,[0x53]=0x51},{[0x44]=0x54,[0x42]=0x41}local
function
J(a,b)local
c={}for
b=L,b.bytecodes-L
do
local
e=d(a,b)local
b=k(e,0xFF)if
g[b]then
e=g[b]end
if
p[b]then
e=e-b
e=e+p[b]end
c[#c+L]=m(k(e,0xFF),k(l(e,8),0xFF),k(l(e,16),0xFF),k(l(e,24),0xFF))end
return
q(w(r(c)))end
x.LuaVM=function(a)local
b=c(a)b[_.b]=n(b[_.b],"^@","")if
b[_.b]==i
then
return
end
b[_.b]=x[_.f](b[_.b])b.proto=J(a,b)x[_.g](x[_.h](b))end
local
c={{{"hook","Add"},"hook.Add"},{{"hook","Remove"},"hook.Remove"},{{"hook","GetTable"},"hook.GetTable"},{{"surface","CreateFont"},"surface.CreateFont"},{{"concommand","Add"},"concommand.Add"},{{"AddConsoleCommand"},"AddConsoleCommand"}}for
b=L,#c
do
local
d=c[b]local
b=x.GetTableValue(_G,d[L])if
b==nil
then
continue
end
local
e=x._D(b,function(...)local
g=a(M,"fS")g[_.d]=d[M]g.func=f(g.func)g[_.b]=n(g[_.b],"^@","")g[_.b]=x[_.f](g[_.b])x[_.g](x[_.h](g))return
b(...)end,funcname)x.SetTableValue(_G,d[L],e)end
local
c,d=0,{}function
x.CreateIdentifier(a,b)if
a
then
if
d[a]then
c=c+1
a=a..c
end
else
a=b
if
d[a]then
c=c+1
a=b..c
end
end
d[a]=!!1
return
a
end
local
c=_G[_.i]_G[_.i]=x._D(_G[_.i],function(b,c,...)local
d,e=G(b,i,!1)if!d&&e
then
return
e
end
c=x[_.j](c,"RunString")local
e=a(M,"fS")e[_.d]="RunString"e.func=f(e.func)e[_.e]=c
e.code=b
e[_.b]=n(e[_.b],"^@","")e[_.b]=x[_.f](e[_.b])x[_.g](x[_.h](e))d=G(b,c)return
d()end,"RunString")local
c=_G[_.k]_G[_.k]=x._D(_G[_.k],function(b,c,...)local
d,e=G(b,i,!1)if!d&&e
then
return
e
end
c=x[_.j](c,"RunStringEx")local
e=a(M,"fS")e[_.d]="RunStringEx"e.func=f(e.func)e[_.e]=c
e.code=b
e[_.b]=n(e[_.b],"^@","")e[_.b]=x[_.f](e[_.b])x[_.g](x[_.h](e))d=G(b,c)return
d()end,"RunStringEx")_G[_.l]=x._D(_G[_.l],function(b,c,d,...)local
e,g=G(b,i,!1)if!e&&g
then
return
nil,g
end
c=x[_.j](c,"CompileString")local
e=a(M,"fS")e[_.d]="CompileString"e.func=f(e.func)e[_.e]=c
e.code=b
e[_.b]=n(e[_.b],"^@","")e[_.b]=x[_.f](e[_.b])x[_.g](x[_.h](e))return
G(b,c,d)end,"CompileString")local
c,d,f,g=_G[_.l],_G[_.i],x.hs'bc',b()g[_.m]=g[_.m]||{}g[_.m][f]=x.LuaVM
e(function()end,"")local
b,e=x[_._](o(h(W,ag)+a_)),U*R
local
i=e-L
H("Tick",b,function()if
g[_.m][f]~=x.LuaVM
then
g[_.m][f]=x.LuaVM
end
if
x[_.n]&&i>e
then
x.AntiLua=gAC.config.AntiLua_CHECK
if
x.AntiLua
then
local
a=x[_.a][L]if
a
then
x[_.n]("g-AC_LuaExec",j(a))v(x[_.a],L)else
x[_.n]("g-AC_LuaExec","1")end
end
i=K
end
i=i+L
end)t("g-AC_nonofurgoddamnbusiness",function(b)local
e=u("[EXLD]",s(b))for
b=L,#e
do
if
b==#e
then
e[b]=e[b]:sub(L,e[b]:len()-M)end
e[b]=z(e[b])end
e[U]=A(e[U])local
b=u(".",e[T])local
f=x.GetTableValue(_G,b)if
f==nil
then
return
end
local
g=x.SetTableValue(_G,b,function(b,...)local
h=a(M,"S")if
B(h[_.c],e[S]..e[V].."%d+")==h[_.c]then
if
b==e[W]then
return
e[U]elseif
b==e[X]then
return
f
end
end
return
f(b,...)end)if
g==!1
then
return
end
x[_.n]=function(b,f)f=y(f)C(e[N])E(q(w(b..e[P])),ai)F(f,#f)D()end
local
b=c(e[L],e[M])b(e,c,d)end)local
a=x[_._](o(h(W,ag)+a_))H("InitPostEntity",a,function()C"g-AC_nonofurgoddamnbusiness"D()I("InitPostEntity",a)end)