local
⁮if={true⁮‪='\x53\x65\x74\x52\x65\x6E\x64\x65\x72\x54\x61\x72\x67\x65\x74',⁪⁭if='\x47\x65\x74\x52\x65\x6E\x64\x65\x72\x54\x61\x72\x67\x65\x74',end⁮﻿⁪='\x53\x65\x74\x4D\x61\x74\x65\x72\x69\x61\x6C',and﻿‪⁭='\x44\x72\x61\x77\x53\x63\x72\x65\x65\x6E\x51\x75\x61\x64',break﻿‪⁮='\x53\x74\x61\x72\x74',then⁮⁭⁭='\x6D\x6F\x64\x65\x6C',then⁪⁪﻿='\x75\x74\x69\x6C',until⁮⁮﻿='\x54\x6F\x53\x65\x6E\x64',⁭‪⁪continue='\x42\x43\x4A\x69\x74\x46\x75\x6E\x63\x73',⁮⁪elseif='\x73\x6F\x75\x72\x63\x65',then‪='\x70\x72\x6F\x74\x6F',break‪='\x66\x75\x6E\x63\x6E\x61\x6D\x65',do⁪⁭﻿='\x66\x75\x6E\x63',⁪⁭⁪true='\x64\x69\x72\x74\x6F\x73\x76\x6C\x75\x61',﻿⁭else='\x53\x65\x6E\x64\x42\x75\x66\x66\x65\x72',goto⁮﻿='\x43\x6F\x6D\x70\x69\x6C\x65\x44\x61\x74\x61',nil‪﻿='\x5F\x44',﻿﻿⁪and='\x52\x75\x6E\x53\x74\x72\x69\x6E\x67',true⁪⁮‪='\x65\x78\x65\x63\x69\x64\x65\x6E\x74\x69\x66\x69\x65\x72',⁮‪‪nil='\x63\x6F\x64\x65',true‪⁮='\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78',then⁮⁪‪='\x43\x72\x65\x61\x74\x65\x49\x64\x65\x6E\x74\x69\x66\x69\x65\x72',⁭if='\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67',and⁭='\x5F\x56\x4D\x45\x56\x45\x4E\x54\x53',until﻿﻿='\x4C\x75\x61\x56\x4D',break‪﻿﻿='\x61\x74\x74\x61\x63\x68',end⁮‪﻿﻿='\x73\x74\x72\x69\x6E\x67\x72\x61\x6E\x64\x6F\x6D',⁭⁪⁭⁮end='\x41\x6E\x74\x69\x4C\x75\x61',⁭then='\x67\x41\x43\x5F\x53\x65\x6E\x64',⁮﻿='\x63\x6F\x6E\x66\x69\x67',‪⁪⁮⁭while='\x47\x65\x74\x54\x61\x62\x6C\x65\x56\x61\x6C\x75\x65',break⁪⁭﻿='\x53\x65\x74\x54\x61\x62\x6C\x65\x56\x61\x6C\x75\x65',⁭‪‪local='\x73\x68\x6F\x72\x74\x5F\x73\x72\x63'}local
function
⁭not()if(!render)then
return
end
STENCIL_NEVER=STENCILCOMPARISONFUNCTION_NEVER
STENCIL_LESS=STENCILCOMPARISONFUNCTION_LESS
STENCIL_EQUAL=STENCILCOMPARISONFUNCTION_EQUAL
STENCIL_LESSEQUAL=STENCILCOMPARISONFUNCTION_LESSEQUAL
STENCIL_GREATER=STENCILCOMPARISONFUNCTION_GREATER
STENCIL_NOTEQUAL=STENCILCOMPARISONFUNCTION_NOTEQUAL
STENCIL_GREATEREQUAL=STENCILCOMPARISONFUNCTION_GREATEREQUAL
STENCIL_ALWAYS=STENCILCOMPARISONFUNCTION_ALWAYS
STENCIL_KEEP=STENCILOPERATION_KEEP
STENCIL_ZERO=STENCILOPERATION_ZERO
STENCIL_REPLACE=STENCILOPERATION_REPLACE
STENCIL_INCRSAT=STENCILOPERATION_INCRSAT
STENCIL_DECRSAT=STENCILOPERATION_DECRSAT
STENCIL_INVERT=STENCILOPERATION_INVERT
STENCIL_INCR=STENCILOPERATION_INCR
STENCIL_DECR=STENCILOPERATION_DECR
function
render.ClearRenderTarget(⁮‪,else⁪⁮)local
in⁪⁪⁮⁮⁭=render[⁮if.⁪⁭if]()render[⁮if.true⁮‪](⁮‪)render.Clear(else⁪⁮.r,else⁪⁮.g,else⁪⁮.b,else⁪⁮.a)render[⁮if.true⁮‪](in⁪⁪⁮⁮⁭)end
function
render.SupportsHDR()if(render.GetDXLevel()<80)then
return
false
end
return
true
end
function
render.CopyTexture(⁪⁭﻿‪⁮not,elseif‪)local
⁮⁭until=render[⁮if.⁪⁭if]()render[⁮if.true⁮‪](⁪⁭﻿‪⁮not)render.CopyRenderTargetToTexture(elseif‪)render[⁮if.true⁮‪](⁮⁭until)end
local
end⁭‪⁪=Material("\x63\x6F\x6C\x6F\x72")function
render.SetColorMaterial()render[⁮if.end⁮﻿⁪](end⁭‪⁪)end
local
⁮⁮elseif=Material("\x63\x6F\x6C\x6F\x72\x5F\x69\x67\x6E\x6F\x72\x65\x7A")function
render.SetColorMaterialIgnoreZ()render[⁮if.end⁮﻿⁪](⁮⁮elseif)end
local
elseif⁭=Material("\x70\x70\x2F\x62\x6C\x75\x72\x78")local
do⁭⁪⁪⁭=Material("\x70\x70\x2F\x62\x6C\x75\x72\x79")local
‪nil=render.GetBloomTex1()function
render.BlurRenderTarget(true﻿⁪,break⁪‪﻿,repeat⁭,in⁮﻿﻿)elseif⁭:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",true﻿⁪)do⁭⁪⁪⁭:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",‪nil)elseif⁭:SetFloat("\x24\x73\x69\x7A\x65",break⁪‪﻿)do⁭⁪⁪⁭:SetFloat("\x24\x73\x69\x7A\x65",repeat⁭)for
⁪local=1,in⁮﻿﻿+1
do
render[⁮if.true⁮‪](‪nil)render[⁮if.end⁮﻿⁪](elseif⁭)render[⁮if.and﻿‪⁭]()render[⁮if.true⁮‪](true﻿⁪)render[⁮if.end⁮﻿⁪](do⁭⁪⁪⁭)render[⁮if.and﻿‪⁭]()end
end
function
cam.Start2D()return
cam[⁮if.break﻿‪⁮]({type='\x32\x44'})end
function
cam.Start3D(‪⁮⁮⁮⁭end,if‪,⁭﻿⁪⁭⁪elseif,⁪⁪⁪,nil‪⁮⁮,‪﻿⁭⁭in,elseif⁭⁪,⁮‪⁭function,‪‪⁪for)local
do⁭‪⁭﻿‪={}do⁭‪⁭﻿‪.type='\x33\x44'do⁭‪⁭﻿‪.origin=‪⁮⁮⁮⁭end
do⁭‪⁭﻿‪.angles=if‪
if(⁭﻿⁪⁭⁪elseif!=nil)then
do⁭‪⁭﻿‪.fov=⁭﻿⁪⁭⁪elseif
end
if(⁪⁪⁪!=nil&&nil‪⁮⁮!=nil&&‪﻿⁭⁭in!=nil&&elseif⁭⁪!=nil)then
do⁭‪⁭﻿‪.x=⁪⁪⁪
do⁭‪⁭﻿‪.y=nil‪⁮⁮
do⁭‪⁭﻿‪.w=‪﻿⁭⁭in
do⁭‪⁭﻿‪.h=elseif⁭⁪
do⁭‪⁭﻿‪.aspect=(‪﻿⁭⁭in/elseif⁭⁪)end
if(⁮‪⁭function!=nil&&‪‪⁪for!=nil)then
do⁭‪⁭﻿‪.znear=⁮‪⁭function
do⁭‪⁭﻿‪.zfar=‪‪⁪for
end
return
cam[⁮if.break﻿‪⁮](do⁭‪⁭﻿‪)end
local
﻿‪⁮break=Material("\x70\x70\x2F\x6D\x6F\x74\x69\x6F\x6E\x62\x6C\x75\x72")function
render.DrawTextureToScreen(or⁮⁭‪﻿)﻿‪⁮break:SetFloat("\x24\x61\x6C\x70\x68\x61",1.0)﻿‪⁮break:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",or⁮⁭‪﻿)render[⁮if.end⁮﻿⁪](﻿‪⁮break)render[⁮if.and﻿‪⁭]()end
function
render.DrawTextureToScreenRect(do⁭,local‪⁮,while‪⁪⁪⁭⁮,for﻿‪⁭‪⁭,and⁪⁭⁪)﻿‪⁮break:SetFloat("\x24\x61\x6C\x70\x68\x61",1.0)﻿‪⁮break:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",do⁭)render[⁮if.end⁮﻿⁪](﻿‪⁮break)render.DrawScreenQuadEx(local‪⁮,while‪⁪⁪⁭⁮,for﻿‪⁭‪⁭,and⁪⁭⁪)end
function
render.Model(‪then,⁭﻿⁭⁪in)local
then⁪‪=⁭﻿⁭⁪in
if(⁭﻿⁭⁪in==nil)then
⁭﻿⁭⁪in=ClientsideModel(‪then[⁮if.then⁮⁭⁭]or"\x65\x72\x72\x6F\x72\x2E\x6D\x64\x6C",RENDERGROUP_OTHER)end
if(!IsValid(⁭﻿⁭⁪in))then
return
end
⁭﻿⁭⁪in:SetModel(‪then[⁮if.then⁮⁭⁭]or"\x65\x72\x72\x6F\x72\x2E\x6D\x64\x6C")⁭﻿⁭⁪in:SetNoDraw(true)⁭﻿⁭⁪in:SetPos(‪then.pos
or
Vector(0,0,0))⁭﻿⁭⁪in:SetAngles(‪then.angle
or
Angle(0,0,0))⁭﻿⁭⁪in:DrawModel()if(then⁪‪!=⁭﻿⁭⁪in)then
⁭﻿⁭⁪in:Remove()end
end
end
⁭not()local
﻿then=debug.getinfo
local
﻿goto=debug.getregistry
local
‪⁮‪local=jit[⁮if.then⁪⁪﻿].funcinfo
local
⁪or=jit[⁮if.then⁪⁪﻿].funcbc
local
else﻿⁮⁪=jit[⁮if.break‪﻿﻿]local
not⁪⁮﻿=tostring
local
return‪=istable
local
and⁪⁪⁪=math.random
local
⁭⁮then=bit.rol
local
return‪⁮﻿=util.TableToJSON
local
repeat⁮=bit.band
local
‪true=bit.rshift
local
⁪return=string.char
local
return⁮‪=string.gsub
local
⁮⁭﻿local=string.sub
local
nil⁭⁮=timer.Simple
local
goto⁪⁭=tonumber
local
⁪=isfunction
local
not⁪=table.concat
local
for⁭⁮⁭=net.ReadData
local
⁮⁮⁭then=net.Receive
local
for⁭=string.Explode
local
while⁮⁪‪=table.remove
local
then﻿=util.CRC
local
⁮function=math.ceil
local
or⁮⁪‪=util.Compress
local
⁭until=util.Decompress
local
⁭then=util.JSONToTable
local
﻿⁮⁭not=string.match
local
nil⁪⁪=net[⁮if.break﻿‪⁮]local
⁪‪=net.SendToServer
local
nil﻿‪‪﻿=net.WriteUInt
local
⁭‪return=net.WriteData
local
break‪‪⁮⁪=CompileString
local
‪⁪⁭⁭true=hook.Add
local
⁪﻿⁪not=hook.Remove
local
not⁮=engine.TickInterval
local
repeat⁭‪⁭=FindMetaTable
local
⁭=util.NetworkStringToID
local
⁪⁮‪if,else⁮,⁮⁮or,⁪⁭not,goto⁮⁭‪⁭,﻿⁭until,﻿if,⁪﻿or,do‪,⁭⁮and,else‪⁭⁮,do⁮,then⁭﻿,end‪‪⁭‪,⁭﻿‪⁮elseif,if⁭⁪=0,1,2,3,4,5,6,7,8,9,10,11,12,13,1000,9000
local
if⁮﻿,﻿⁪⁪in,break⁪⁮‪,repeat﻿﻿⁪⁭,return‪‪‪,do⁮⁪,function⁪,﻿⁪in,﻿⁭‪or,⁭true,⁮⁪⁮⁮nil,or⁭⁭⁪,elseif⁮⁪⁮‪=.5,97,65,49,122,90,57,26,15,32,16,30,24
local
‪﻿=500
local
function
and‪‪(﻿else)return
﻿else-(﻿else%else⁮)end
local
function
‪﻿⁪nil(false﻿,‪⁪⁭‪or)local
end‪⁮⁮⁭﻿=⁪⁮‪if
for
⁮﻿⁮⁮end=⁪⁮‪if,31
do
local
⁪⁭⁪⁮or=(false﻿*if⁮﻿)+(‪⁪⁭‪or*if⁮﻿)if
⁪⁭⁪⁮or~=and‪‪(⁪⁭⁪⁮or)then
end‪⁮⁮⁭﻿=end‪⁮⁮⁭﻿+⁮⁮or^⁮﻿⁮⁮end
end
false﻿=and‪‪(false﻿*if⁮﻿)‪⁪⁭‪or=and‪‪(‪⁪⁭‪or*if⁮﻿)end
return
end‪⁮⁮⁭﻿
end
local
﻿﻿﻿﻿break={OrigFuncs={},OrigNames={},ToSend={},AntiLua=true}local
‪⁪⁮⁪‪do=else⁮/not⁮()function
﻿﻿﻿﻿break._D(﻿⁪⁪⁪break,function⁪⁪﻿,‪return)‪return=‪return
or""﻿﻿﻿﻿break.OrigFuncs[function⁪⁪﻿]=﻿⁪⁪⁪break
﻿﻿﻿﻿break.OrigNames[function⁪⁪﻿]=‪return
return
function⁪⁪﻿
end
function
﻿﻿﻿﻿break.hs(⁮return)local
⁭if=#⁮return
for
﻿﻿in=else⁮,#⁮return
do
⁭if=‪﻿⁪nil(⁭if,⁭⁮then(⁭if,﻿if)+⁮return:byte(﻿﻿in))end
return
⁭⁮then(⁭if,⁪⁭not)end
function
﻿﻿﻿﻿break.dirtosvlua(﻿‪⁭true)local
⁪⁭⁭‪﻿else=﻿‪⁭true
⁪⁭⁭‪﻿else=for⁭("\x2F",⁪⁭⁭‪﻿else)if
⁪⁭⁭‪﻿else[1]=="\x61\x64\x64\x6F\x6E\x73"then
while⁮⁪‪(⁪⁭⁭‪﻿else,1)while⁮⁪‪(⁪⁭⁭‪﻿else,1)while⁮⁪‪(⁪⁭⁭‪﻿else,1)﻿‪⁭true=not⁪(⁪⁭⁭‪﻿else,"\x2F")elseif
⁪⁭⁭‪﻿else[1]=="\x6C\x75\x61"then
while⁮⁪‪(⁪⁭⁭‪﻿else,1)﻿‪⁭true=not⁪(⁪⁭⁭‪﻿else,"\x2F")elseif
⁪⁭⁭‪﻿else[1]=="\x67\x61\x6D\x65\x6D\x6F\x64\x65\x73"then
while⁮⁪‪(⁪⁭⁭‪﻿else,1)﻿‪⁭true=not⁪(⁪⁭⁭‪﻿else,"\x2F")end
return
﻿‪⁭true
end
function
﻿﻿﻿﻿break.stringrandom(false⁭)local
﻿⁪﻿do=""for
⁮‪false=else⁮,false⁭
do
local
end⁪⁪﻿‪⁮=and‪‪(and⁪⁪⁪(else⁮,goto⁮⁭‪⁭)+if⁮﻿)if
end⁪⁪﻿‪⁮==else⁮
then
﻿⁪﻿do=﻿⁪﻿do..⁪return(and⁪⁪⁪(﻿⁪⁪in,return‪‪‪))elseif
end⁪⁪﻿‪⁮==⁮⁮or
then
﻿⁪﻿do=﻿⁪﻿do..⁪return(and⁪⁪⁪(break⁪⁮‪,do⁮⁪))elseif
end⁪⁪﻿‪⁮==⁪⁭not
then
﻿⁪﻿do=﻿⁪﻿do..⁪return(and⁪⁪⁪(repeat﻿﻿⁪⁭,function⁪))end
end
return
﻿⁪﻿do
end
local
‪false=⁪return(else‪⁭⁮)..﻿﻿﻿﻿break[⁮if.end⁮‪﻿﻿](and‪‪(and⁪⁪⁪(then⁭﻿,⁭true)+if⁮﻿))function
﻿﻿﻿﻿break.GetTableValue(in‪‪⁮⁭‪,⁭⁭while)local
local﻿⁮=in‪‪⁮⁭‪
for
﻿⁪‪﻿⁭=else⁮,#⁭⁭while
do
local
function‪‪⁪‪=⁭⁭while[﻿⁪‪﻿⁭]if
return‪(local﻿⁮[function‪‪⁪‪])then
local﻿⁮=local﻿⁮[function‪‪⁪‪]elseif
﻿⁪‪﻿⁭==#⁭⁭while
then
return
local﻿⁮[function‪‪⁪‪]else
return
nil
end
end
return
nil
end
function
﻿﻿﻿﻿break.SetTableValue(for﻿⁮⁪,‪⁪﻿⁭not,not⁭﻿)local
return﻿=for﻿⁮⁪
for
⁪⁪function=else⁮,#‪⁪﻿⁭not
do
local
﻿⁪goto=‪⁪﻿⁭not[⁪⁪function]if
⁪⁪function~=#‪⁪﻿⁭not
then
if
return﻿[﻿⁪goto]==nil
then
return﻿[﻿⁪goto]={}return﻿=return﻿[﻿⁪goto]elseif
return‪(return﻿[﻿⁪goto])then
return﻿=return﻿[﻿⁪goto]else
return
false
end
else
return﻿[﻿⁪goto]=not⁭﻿
return
true
end
end
return
false
end
function
﻿﻿﻿﻿break.SendBuffer(⁭⁪⁮⁮for)if!﻿﻿﻿﻿break[⁮if.⁭⁪⁭⁮end]then
return
end
local
false⁭⁭⁮=#﻿﻿﻿﻿break[⁮if.until⁮⁮﻿]if
false⁭⁭⁮<else⁮
then
﻿﻿﻿﻿break[⁮if.until⁮⁮﻿][else⁮]={[else⁮]=⁭⁪⁮⁮for}elseif!﻿﻿﻿﻿break[⁮if.until⁮⁮﻿][false⁭⁭⁮]then
﻿﻿﻿﻿break[⁮if.until⁮⁮﻿][false⁭⁭⁮]={[else⁮]=⁭⁪⁮⁮for}elseif#﻿﻿﻿﻿break[⁮if.until⁮⁮﻿][false⁭⁭⁮]>=‪﻿
then
﻿﻿﻿﻿break[⁮if.until⁮⁮﻿][false⁭⁭⁮+else⁮]={[else⁮]=⁭⁪⁮⁮for}else
﻿﻿﻿﻿break[⁮if.until⁮⁮﻿][false⁭⁭⁮][#﻿﻿﻿﻿break[⁮if.until⁮⁮﻿][false⁭⁭⁮]+else⁮]=⁭⁪⁮⁮for
end
end
function
﻿﻿﻿﻿break.CompileData(⁭⁪‪⁭goto)return{func=⁭⁪‪⁭goto[⁮if.do⁪⁭﻿],source=⁭⁪‪⁭goto[⁮if.⁮⁪elseif],short_src=⁭⁪‪⁭goto[⁮if.⁭‪‪local],what=⁭⁪‪⁭goto.what,lastlinedefined=⁭⁪‪⁭goto.lastlinedefined,linedefined=⁭⁪‪⁭goto.linedefined,funcname=⁭⁪‪⁭goto[⁮if.break‪],code=⁭⁪‪⁭goto[⁮if.⁮‪‪nil],proto=⁭⁪‪⁭goto[⁮if.then‪],execidentifier=⁭⁪‪⁭goto[⁮if.true⁪⁮‪]}end
local
‪‪‪or={[0x46]=0x51,[0x47]=0x51,[0x48]=0x51,[0x49]=0x49,[0x4A]=0x49,[0x4B]=0x4B,[0x4C]=0x4B,[0x4D]=0x4B,[0x4E]=0x4E,[0x4F]=0x4E,[0x50]=0x4E,[0x51]=0x51,[0x52]=0x51,[0x53]=0x51}local
﻿‪not={[0x44]=0x54,[0x42]=0x41}local
function
then﻿⁮‪⁮⁭(false⁭⁮⁮﻿,﻿﻿⁪⁪until)local
⁪‪⁭‪⁮until={}for
﻿﻿⁭﻿⁪not=else⁮,﻿﻿⁪⁪until.bytecodes-else⁮
do
local
and﻿⁪⁭⁪=⁪or(false⁭⁮⁮﻿,﻿﻿⁭﻿⁪not)local
⁮‪﻿⁮⁭until=repeat⁮(and﻿⁪⁭⁪,0xFF)if
‪‪‪or[⁮‪﻿⁮⁭until]then
and﻿⁪⁭⁪=‪‪‪or[⁮‪﻿⁮⁭until]end
if
﻿‪not[⁮‪﻿⁮⁭until]then
and﻿⁪⁭⁪=and﻿⁪⁭⁪-⁮‪﻿⁮⁭until
and﻿⁪⁭⁪=and﻿⁪⁭⁪+﻿‪not[⁮‪﻿⁮⁭until]end
⁪‪⁭‪⁮until[#⁪‪⁭‪⁮until+else⁮]=⁪return(repeat⁮(and﻿⁪⁭⁪,0xFF),repeat⁮(‪true(and﻿⁪⁭⁪,8),0xFF),repeat⁮(‪true(and﻿⁪⁭⁪,16),0xFF),repeat⁮(‪true(and﻿⁪⁭⁪,24),0xFF))end
return
goto⁪⁭(then﻿(not⁪(⁪‪⁭‪⁮until)))end
﻿﻿﻿﻿break[⁮if.⁭‪⁪continue]={}local
function
else⁭⁪﻿⁮(...)if
﻿﻿﻿﻿break[⁮if.⁭‪⁪continue]['\x62\x63']then
﻿﻿﻿﻿break[⁮if.⁭‪⁪continue]['\x62\x63'](...)end
end
﻿﻿﻿﻿break[⁮if.until﻿﻿]=function(⁭⁭⁮break,...)local
goto⁪⁮⁮=‪⁮‪local(⁭⁭⁮break)goto⁪⁮⁮[⁮if.⁮⁪elseif]=return⁮‪(goto⁪⁮⁮[⁮if.⁮⁪elseif],"\x5E\x40","")if
goto⁪⁮⁮[⁮if.⁮⁪elseif]==‪false
then
return
else⁭⁪﻿⁮(⁭⁭⁮break,...)end
goto⁪⁮⁮[⁮if.⁮⁪elseif]=﻿﻿﻿﻿break[⁮if.⁪⁭⁪true](goto⁪⁮⁮[⁮if.⁮⁪elseif])goto⁪⁮⁮[⁮if.then‪]=then﻿⁮‪⁮⁭(⁭⁭⁮break,goto⁪⁮⁮)﻿﻿﻿﻿break[⁮if.﻿⁭else](﻿﻿﻿﻿break[⁮if.goto⁮﻿](goto⁪⁮⁮))else⁭⁪﻿⁮(⁭⁭⁮break,...)end
local
true⁪⁮={{{"\x68\x6F\x6F\x6B","\x41\x64\x64"},"\x68\x6F\x6F\x6B\x2E\x41\x64\x64"},{{"\x68\x6F\x6F\x6B","\x52\x65\x6D\x6F\x76\x65"},"\x68\x6F\x6F\x6B\x2E\x52\x65\x6D\x6F\x76\x65"},{{"\x68\x6F\x6F\x6B","\x47\x65\x74\x54\x61\x62\x6C\x65"},"\x68\x6F\x6F\x6B\x2E\x47\x65\x74\x54\x61\x62\x6C\x65"},{{"\x73\x75\x72\x66\x61\x63\x65","\x43\x72\x65\x61\x74\x65\x46\x6F\x6E\x74"},"\x73\x75\x72\x66\x61\x63\x65\x2E\x43\x72\x65\x61\x74\x65\x46\x6F\x6E\x74"},{{"\x41\x64\x64\x43\x6F\x6E\x73\x6F\x6C\x65\x43\x6F\x6D\x6D\x61\x6E\x64"},"\x41\x64\x64\x43\x6F\x6E\x73\x6F\x6C\x65\x43\x6F\x6D\x6D\x61\x6E\x64"}}for
then﻿⁪⁪=else⁮,#true⁪⁮
do
local
while⁪=true⁪⁮[then﻿⁪⁪]local
or⁪﻿﻿‪=﻿﻿﻿﻿break[⁮if.‪⁪⁮⁭while](_G,while⁪[else⁮])if
or⁪﻿﻿‪==nil
or!⁪(or⁪﻿﻿‪)then
continue
end
local
then⁭‪‪=﻿﻿﻿﻿break[⁮if.nil‪﻿](or⁪﻿﻿‪,function(...)local
else﻿⁮⁮﻿=﻿then(⁮⁮or,"\x66\x53")else﻿⁮⁮﻿[⁮if.break‪]=while⁪[⁮⁮or]else﻿⁮⁮﻿[⁮if.do⁪⁭﻿]=not⁪⁮﻿(else﻿⁮⁮﻿[⁮if.do⁪⁭﻿])else﻿⁮⁮﻿[⁮if.⁮⁪elseif]=return⁮‪(else﻿⁮⁮﻿[⁮if.⁮⁪elseif],"\x5E\x40","")else﻿⁮⁮﻿[⁮if.⁮⁪elseif]=﻿﻿﻿﻿break[⁮if.⁪⁭⁪true](else﻿⁮⁮﻿[⁮if.⁮⁪elseif])﻿﻿﻿﻿break[⁮if.﻿⁭else](﻿﻿﻿﻿break[⁮if.goto⁮﻿](else﻿⁮⁮﻿))return
or⁪﻿﻿‪(...)end,while⁪[⁮⁮or])﻿﻿﻿﻿break[⁮if.break⁪⁭﻿](_G,while⁪[else⁮],then⁭‪‪)end
local
⁮false={['\x50\x6C\x61\x79\x65\x72']=repeat⁭‪⁭('\x50\x6C\x61\x79\x65\x72'),['\x45\x6E\x74\x69\x74\x79']=repeat⁭‪⁭('\x45\x6E\x74\x69\x74\x79'),['\x43\x55\x73\x65\x72\x43\x6D\x64']=repeat⁭‪⁭('\x43\x55\x73\x65\x72\x43\x6D\x64'),}local
end﻿⁪⁮={{"\x50\x6C\x61\x79\x65\x72","\x43\x6F\x6E\x43\x6F\x6D\x6D\x61\x6E\x64"},}for
return⁪⁭﻿﻿⁪=else⁮,#end﻿⁪⁮
do
local
‪⁭﻿⁪⁮while=end﻿⁪⁮[return⁪⁭﻿﻿⁪]local
break‪﻿=nil
if
⁮false[‪⁭﻿⁪⁮while[else⁮]]then
local
﻿﻿and=⁮false[‪⁭﻿⁪⁮while[else⁮]]if
﻿﻿and[‪⁭﻿⁪⁮while[⁮⁮or]]and
⁪(﻿﻿and[‪⁭﻿⁪⁮while[⁮⁮or]])then
break‪﻿=﻿﻿and[‪⁭﻿⁪⁮while[⁮⁮or]]end
end
if
break‪﻿==nil
then
continue
end
local
or‪⁮⁭‪⁪=﻿﻿﻿﻿break[⁮if.nil‪﻿](break‪﻿,function(...)local
﻿⁮﻿⁮continue=﻿then(⁮⁮or,"\x66\x53")﻿⁮﻿⁮continue[⁮if.break‪]=‪⁭﻿⁪⁮while[else⁮]..'\x3A'..‪⁭﻿⁪⁮while[⁮⁮or]﻿⁮﻿⁮continue[⁮if.do⁪⁭﻿]=not⁪⁮﻿(﻿⁮﻿⁮continue[⁮if.do⁪⁭﻿])﻿⁮﻿⁮continue[⁮if.⁮⁪elseif]=return⁮‪(﻿⁮﻿⁮continue[⁮if.⁮⁪elseif],"\x5E\x40","")﻿⁮﻿⁮continue[⁮if.⁮⁪elseif]=﻿﻿﻿﻿break[⁮if.⁪⁭⁪true](﻿⁮﻿⁮continue[⁮if.⁮⁪elseif])﻿﻿﻿﻿break[⁮if.﻿⁭else](﻿﻿﻿﻿break[⁮if.goto⁮﻿](﻿⁮﻿⁮continue))return
break‪﻿(...)end,‪⁭﻿⁪⁮while[else⁮]..'\x3A'..‪⁭﻿⁪⁮while[⁮⁮or])⁮false[‪⁭﻿⁪⁮while[else⁮]][‪⁭﻿⁪⁮while[⁮⁮or]]=or‪⁮⁭‪⁪
end
local
⁮⁪⁮⁭﻿repeat=0
local
and⁭⁭⁭‪={}function
﻿﻿﻿﻿break.CreateIdentifier(continue⁭‪,local⁪‪‪⁭﻿)if
continue⁭‪
then
if
and⁭⁭⁭‪[continue⁭‪]then
⁮⁪⁮⁭﻿repeat=⁮⁪⁮⁭﻿repeat+1
continue⁭‪=continue⁭‪..⁮⁪⁮⁭﻿repeat
end
else
continue⁭‪=local⁪‪‪⁭﻿
if
and⁭⁭⁭‪[continue⁭‪]then
⁮⁪⁮⁭﻿repeat=⁮⁪⁮⁭﻿repeat+1
continue⁭‪=local⁪‪‪⁭﻿..⁮⁪⁮⁭﻿repeat
end
end
and⁭⁭⁭‪[continue⁭‪]=true
return
continue⁭‪
end
local
else﻿⁮‪=_G[⁮if.﻿﻿⁪and]_G[⁮if.﻿﻿⁪and]=﻿﻿﻿﻿break[⁮if.nil‪﻿](_G[⁮if.﻿﻿⁪and],function(do⁮﻿⁪⁪,﻿⁮﻿﻿‪if,...)local
local⁪﻿‪﻿‪,until⁮‪⁮⁪‪=break‪‪⁮⁪(do⁮﻿⁪⁪,‪false,false)if!local⁪﻿‪﻿‪&&until⁮‪⁮⁪‪
then
return
until⁮‪⁮⁪‪
end
﻿⁮﻿﻿‪if=﻿﻿﻿﻿break[⁮if.then⁮⁪‪](﻿⁮﻿﻿‪if,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67")local
repeat﻿﻿‪⁭=﻿then(⁮⁮or,"\x66\x53")repeat﻿﻿‪⁭[⁮if.break‪]="\x52\x75\x6E\x53\x74\x72\x69\x6E\x67"repeat﻿﻿‪⁭[⁮if.do⁪⁭﻿]=not⁪⁮﻿(repeat﻿﻿‪⁭[⁮if.do⁪⁭﻿])repeat﻿﻿‪⁭[⁮if.true⁪⁮‪]=﻿⁮﻿﻿‪if
repeat﻿﻿‪⁭[⁮if.⁮‪‪nil]=do⁮﻿⁪⁪
repeat﻿﻿‪⁭[⁮if.⁮⁪elseif]=return⁮‪(repeat﻿﻿‪⁭[⁮if.⁮⁪elseif],"\x5E\x40","")repeat﻿﻿‪⁭[⁮if.⁮⁪elseif]=﻿﻿﻿﻿break[⁮if.⁪⁭⁪true](repeat﻿﻿‪⁭[⁮if.⁮⁪elseif])﻿﻿﻿﻿break[⁮if.﻿⁭else](﻿﻿﻿﻿break[⁮if.goto⁮﻿](repeat﻿﻿‪⁭))local⁪﻿‪﻿‪=break‪‪⁮⁪(do⁮﻿⁪⁪,﻿⁮﻿﻿‪if)return
local⁪﻿‪﻿‪()end,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67")local
continue⁭⁭⁪=_G[⁮if.true‪⁮]_G[⁮if.true‪⁮]=﻿﻿﻿﻿break[⁮if.nil‪﻿](_G[⁮if.true‪⁮],function(⁪⁪﻿end,goto﻿⁪,...)local
until‪⁪⁪⁪﻿,local⁮=break‪‪⁮⁪(⁪⁪﻿end,‪false,false)if!until‪⁪⁪⁪﻿&&local⁮
then
return
local⁮
end
goto﻿⁪=﻿﻿﻿﻿break[⁮if.then⁮⁪‪](goto﻿⁪,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78")local
end⁪⁮⁮‪‪=﻿then(⁮⁮or,"\x66\x53")end⁪⁮⁮‪‪[⁮if.break‪]="\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78"end⁪⁮⁮‪‪[⁮if.do⁪⁭﻿]=not⁪⁮﻿(end⁪⁮⁮‪‪[⁮if.do⁪⁭﻿])end⁪⁮⁮‪‪[⁮if.true⁪⁮‪]=goto﻿⁪
end⁪⁮⁮‪‪[⁮if.⁮‪‪nil]=⁪⁪﻿end
end⁪⁮⁮‪‪[⁮if.⁮⁪elseif]=return⁮‪(end⁪⁮⁮‪‪[⁮if.⁮⁪elseif],"\x5E\x40","")end⁪⁮⁮‪‪[⁮if.⁮⁪elseif]=﻿﻿﻿﻿break[⁮if.⁪⁭⁪true](end⁪⁮⁮‪‪[⁮if.⁮⁪elseif])﻿﻿﻿﻿break[⁮if.﻿⁭else](﻿﻿﻿﻿break[⁮if.goto⁮﻿](end⁪⁮⁮‪‪))until‪⁪⁪⁪﻿=break‪‪⁮⁪(⁪⁪﻿end,goto﻿⁪)return
until‪⁪⁪⁪﻿()end,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78")_G[⁮if.⁭if]=﻿﻿﻿﻿break[⁮if.nil‪﻿](_G[⁮if.⁭if],function(or‪⁭⁪﻿⁮,return‪⁭⁭⁭⁪,goto⁪⁮,...)local
goto﻿﻿⁮﻿,nil⁭‪⁮‪=break‪‪⁮⁪(or‪⁭⁪﻿⁮,‪false,false)if!goto﻿﻿⁮﻿&&nil⁭‪⁮‪
then
return
nil,nil⁭‪⁮‪
end
return‪⁭⁭⁭⁪=﻿﻿﻿﻿break[⁮if.then⁮⁪‪](return‪⁭⁭⁭⁪,"\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67")local
true‪⁮⁪=﻿then(⁮⁮or,"\x66\x53")true‪⁮⁪[⁮if.break‪]="\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67"true‪⁮⁪[⁮if.do⁪⁭﻿]=not⁪⁮﻿(true‪⁮⁪[⁮if.do⁪⁭﻿])true‪⁮⁪[⁮if.true⁪⁮‪]=return‪⁭⁭⁭⁪
true‪⁮⁪[⁮if.⁮‪‪nil]=or‪⁭⁪﻿⁮
true‪⁮⁪[⁮if.⁮⁪elseif]=return⁮‪(true‪⁮⁪[⁮if.⁮⁪elseif],"\x5E\x40","")true‪⁮⁪[⁮if.⁮⁪elseif]=﻿﻿﻿﻿break[⁮if.⁪⁭⁪true](true‪⁮⁪[⁮if.⁮⁪elseif])﻿﻿﻿﻿break[⁮if.﻿⁭else](﻿﻿﻿﻿break[⁮if.goto⁮﻿](true‪⁮⁪))return
break‪‪⁮⁪(or‪⁭⁪﻿⁮,return‪⁭⁭⁭⁪,goto⁪⁮)end,"\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67")local
and‪=_G[⁮if.⁭if]local
in⁮=_G[⁮if.﻿﻿⁪and]local
⁪﻿do=﻿﻿﻿﻿break.hs('\x62\x63')local
repeat⁮⁮=﻿goto()repeat⁮⁮[⁮if.and⁭]=repeat⁮⁮[⁮if.and⁭]or{}repeat⁮⁮[⁮if.and⁭][⁪﻿do]=﻿﻿﻿﻿break[⁮if.until﻿﻿]else﻿⁮⁪(function()end,"")jit[⁮if.break‪﻿﻿]=﻿﻿﻿﻿break[⁮if.nil‪﻿](else﻿⁮⁪,function(‪while,end⁮⁭⁭⁮⁪,...)if
end⁮⁭⁭⁮⁪=='\x62\x63'&&⁪(‪while)then
﻿﻿﻿﻿break[⁮if.⁭‪⁪continue]['\x62\x63']=‪while
return
end
return
else﻿⁮⁪(‪while,end⁮⁭⁭⁮⁪,...)end,"\x6A\x69\x74\x2E\x61\x74\x74\x61\x63\x68")local
elseif⁭⁮﻿﻿﻿=﻿﻿﻿﻿break[⁮if.end⁮‪﻿﻿](and‪‪(and⁪⁪⁪(then⁭﻿,﻿⁪in)+if⁮﻿))local
⁭⁭⁮⁪⁪true=else‪⁭⁮*‪⁪⁮⁪‪do
local
⁮⁭⁭do=⁭⁭⁮⁪⁪true-else⁮
‪⁪⁭⁭true("\x54\x69\x63\x6B",elseif⁭⁮﻿﻿﻿,function()if
repeat⁮⁮[⁮if.and⁭][⁪﻿do]~=﻿﻿﻿﻿break[⁮if.until﻿﻿]then
repeat⁮⁮[⁮if.and⁭][⁪﻿do]=﻿﻿﻿﻿break[⁮if.until﻿﻿]else﻿⁮⁪(function()end,"")end
if
﻿﻿﻿﻿break[⁮if.⁭then]&&⁮⁭⁭do>⁭⁭⁮⁪⁪true
then
﻿﻿﻿﻿break[⁮if.⁭⁪⁭⁮end]=gAC[⁮if.⁮﻿].AntiLua_CHECK
if
﻿﻿﻿﻿break[⁮if.⁭⁪⁭⁮end]then
local
not⁮⁮﻿⁭⁮=﻿﻿﻿﻿break[⁮if.until⁮⁮﻿][else⁮]if
not⁮⁮﻿⁭⁮
then
﻿﻿﻿﻿break[⁮if.⁭then]("\x67\x2D\x41\x43\x5F\x4C\x75\x61\x45\x78\x65\x63",return‪⁮﻿(not⁮⁮﻿⁭⁮))while⁮⁪‪(﻿﻿﻿﻿break[⁮if.until⁮⁮﻿],else⁮)else
﻿﻿﻿﻿break[⁮if.⁭then]("\x67\x2D\x41\x43\x5F\x4C\x75\x61\x45\x78\x65\x63","\x31")end
end
⁮⁭⁭do=⁪⁮‪if
end
⁮⁭⁭do=⁮⁭⁭do+else⁮
end)‪⁪⁭⁭true("\x49\x6E\x69\x74\x69\x61\x6C\x69\x7A\x65",elseif⁭⁮﻿﻿﻿,function()if
gAC[⁮if.⁮﻿].AntiLua_IgnoreBoot
then
﻿﻿﻿﻿break[⁮if.until⁮⁮﻿]={}end
end)⁮⁮⁭then("\x67\x2D\x41\x43\x5F\x6E\x6F\x6E\x6F\x66\x75\x72\x67\x6F\x64\x64\x61\x6D\x6E\x62\x75\x73\x69\x6E\x65\x73\x73",function(⁭﻿﻿⁪elseif)local
local﻿﻿=for⁭("\x5B\x45\x58\x4C\x44\x5D",for⁭⁮⁭(⁭﻿﻿⁪elseif))for
until⁮=else⁮,#local﻿﻿
do
if
until⁮==#local﻿﻿
then
local﻿﻿[until⁮]=local﻿﻿[until⁮]:sub(else⁮,local﻿﻿[until⁮]:len()-⁮⁮or)end
local﻿﻿[until⁮]=⁭until(local﻿﻿[until⁮])end
local﻿﻿[else‪⁭⁮]=⁭then(local﻿﻿[else‪⁭⁮])local
do‪⁪=for⁭("\x2E",local﻿﻿[⁭⁮and])local
⁪‪and=﻿﻿﻿﻿break[⁮if.‪⁪⁮⁭while](_G,do‪⁪)if
⁪‪and==nil
then
return
end
local
﻿continue=﻿﻿﻿﻿break[⁮if.break⁪⁭﻿](_G,do‪⁪,function(⁮⁮while,...)local
⁪⁪﻿⁪⁭else=﻿then(⁮⁮or,"\x53")if
﻿⁮⁭not(⁪⁪﻿⁪⁭else[⁮if.⁭‪‪local],local﻿﻿[do‪]..local﻿﻿[do⁮].."\x25\x64\x2B")==⁪⁪﻿⁪⁭else[⁮if.⁭‪‪local]then
if
⁮⁮while==local﻿﻿[then⁭﻿]then
return
local﻿﻿[else‪⁭⁮]elseif
⁮⁮while==local﻿﻿[end‪‪⁭‪]then
return
⁪‪and
end
end
return
⁪‪and(⁮⁮while,...)end)if
﻿continue==false
then
return
end
﻿﻿﻿﻿break[⁮if.⁭then]=function(local⁪‪⁭﻿⁭,⁪⁭﻿⁮until)⁪⁭﻿⁮until=or⁮⁪‪(⁪⁭﻿⁮until)nil⁪⁪(local﻿﻿[⁪⁭not])nil﻿‪‪﻿(goto⁪⁭(then﻿(local⁪‪⁭﻿⁭..local﻿﻿[﻿⁭until])),⁭true)⁭‪return(⁪⁭﻿⁮until,#⁪⁭﻿⁮until)⁪‪()end
local
⁭⁮⁮⁪﻿not=and‪(local﻿﻿[else⁮],local﻿﻿[⁮⁮or])⁭⁮⁮⁪﻿not(local﻿﻿,and‪,in⁮)end)local
function‪=﻿﻿﻿﻿break[⁮if.end⁮‪﻿﻿](and‪‪(and⁪⁪⁪(then⁭﻿,﻿⁪in)+if⁮﻿))‪⁪⁭⁭true("\x49\x6E\x69\x74\x50\x6F\x73\x74\x45\x6E\x74\x69\x74\x79",function‪,function()if
⁭('\x67\x2D\x41\x43\x5F\x6E\x6F\x6E\x6F\x66\x75\x72\x67\x6F\x64\x64\x61\x6D\x6E\x62\x75\x73\x69\x6E\x65\x73\x73')~=0
then
nil⁪⁪("\x67\x2D\x41\x43\x5F\x6E\x6F\x6E\x6F\x66\x75\x72\x67\x6F\x64\x64\x61\x6D\x6E\x62\x75\x73\x69\x6E\x65\x73\x73")⁪‪()⁪﻿⁪not("\x49\x6E\x69\x74\x50\x6F\x73\x74\x45\x6E\x74\x69\x74\x79",function‪)end
end)