local
in﻿={and⁭='\x53\x65\x74\x52\x65\x6E\x64\x65\x72\x54\x61\x72\x67\x65\x74',⁭⁭⁭while='\x47\x65\x74\x52\x65\x6E\x64\x65\x72\x54\x61\x72\x67\x65\x74',do⁪﻿⁪='\x53\x65\x74\x4D\x61\x74\x65\x72\x69\x61\x6C',‪⁭then='\x44\x72\x61\x77\x53\x63\x72\x65\x65\x6E\x51\x75\x61\x64',⁭‪⁪continue='\x53\x74\x61\x72\x74',﻿‪goto='\x6D\x6F\x64\x65\x6C',⁪‪⁪='\x75\x74\x69\x6C',continue⁮='\x54\x6F\x53\x65\x6E\x64',⁭⁪⁪nil='\x42\x43\x4A\x69\x74\x46\x75\x6E\x63\x73',elseif‪﻿='\x73\x6F\x75\x72\x63\x65',⁮end='\x70\x72\x6F\x74\x6F',repeat⁪‪﻿='\x66\x75\x6E\x63\x6E\x61\x6D\x65',‪end='\x66\x75\x6E\x63',elseif⁭⁮⁪='\x64\x69\x72\x74\x6F\x73\x76\x6C\x75\x61',‪⁪not='\x53\x65\x6E\x64\x42\x75\x66\x66\x65\x72',⁪or='\x43\x6F\x6D\x70\x69\x6C\x65\x44\x61\x74\x61',⁭﻿⁭='\x5F\x44',repeat﻿='\x52\x75\x6E\x53\x74\x72\x69\x6E\x67',⁪⁮nil='\x65\x78\x65\x63\x69\x64\x65\x6E\x74\x69\x66\x69\x65\x72',elseif⁭⁪⁮='\x63\x6F\x64\x65',⁮⁭else='\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78',‪break='\x43\x72\x65\x61\x74\x65\x49\x64\x65\x6E\x74\x69\x66\x69\x65\x72',⁮function='\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67',false﻿⁮='\x5F\x56\x4D\x45\x56\x45\x4E\x54\x53',continue‪⁭='\x4C\x75\x61\x56\x4D',return﻿='\x61\x74\x74\x61\x63\x68',﻿﻿﻿or='\x73\x74\x72\x69\x6E\x67\x72\x61\x6E\x64\x6F\x6D',elseif⁮⁮⁪='\x41\x6E\x74\x69\x4C\x75\x61',⁪‪﻿continue='\x67\x41\x43\x5F\x53\x65\x6E\x64',in﻿⁪⁮﻿='\x63\x6F\x6E\x66\x69\x67',‪﻿local='\x47\x65\x74\x54\x61\x62\x6C\x65\x56\x61\x6C\x75\x65',﻿do='\x53\x65\x74\x54\x61\x62\x6C\x65\x56\x61\x6C\x75\x65',do﻿⁭⁮﻿='\x73\x68\x6F\x72\x74\x5F\x73\x72\x63'}local
function
‪false()if(!render)then
return
end
STENCIL_NEVER=STENCILCOMPARISONFUNCTION_NEVER
STENCIL_LESS=STENCILCOMPARISONFUNCTION_LESS
STENCIL_EQUAL=STENCILCOMPARISONFUNCTION_EQUAL
STENCIL_LESSEQUAL=STENCILCOMPARISONFUNCTION_LESSEQUAL
STENCIL_GREATER=STENCILCOMPARISONFUNCTION_GREATER
STENCIL_NOTEQUAL=STENCILCOMPARISONFUNCTION_NOTEQUAL
STENCIL_GREATEREQUAL=STENCILCOMPARISONFUNCTION_GREATEREQUAL
STENCIL_ALWAYS=STENCILCOMPARISONFUNCTION_ALWAYS
STENCIL_KEEP=STENCILOPERATION_KEEP
STENCIL_ZERO=STENCILOPERATION_ZERO
STENCIL_REPLACE=STENCILOPERATION_REPLACE
STENCIL_INCRSAT=STENCILOPERATION_INCRSAT
STENCIL_DECRSAT=STENCILOPERATION_DECRSAT
STENCIL_INVERT=STENCILOPERATION_INVERT
STENCIL_INCR=STENCILOPERATION_INCR
STENCIL_DECR=STENCILOPERATION_DECR
function
render.ClearRenderTarget(then⁪﻿⁭⁭⁪,⁮⁭‪‪)local
﻿⁪⁪⁪⁭or=render[in﻿.⁭⁭⁭while]()render[in﻿.and⁭](then⁪﻿⁭⁭⁪)render.Clear(⁮⁭‪‪.r,⁮⁭‪‪.g,⁮⁭‪‪.b,⁮⁭‪‪.a)render[in﻿.and⁭](﻿⁪⁪⁪⁭or)end
function
render.SupportsHDR()if(render.GetDXLevel()<80)then
return
false
end
return
true
end
function
render.CopyTexture(⁭nil,⁮﻿⁭false)local
end﻿‪﻿⁭⁭=render[in﻿.⁭⁭⁭while]()render[in﻿.and⁭](⁭nil)render.CopyRenderTargetToTexture(⁮﻿⁭false)render[in﻿.and⁭](end﻿‪﻿⁭⁭)end
local
⁪⁮⁭⁭﻿goto=Material("\x63\x6F\x6C\x6F\x72")function
render.SetColorMaterial()render[in﻿.do⁪﻿⁪](⁪⁮⁭⁭﻿goto)end
local
﻿⁪‪﻿﻿end=Material("\x63\x6F\x6C\x6F\x72\x5F\x69\x67\x6E\x6F\x72\x65\x7A")function
render.SetColorMaterialIgnoreZ()render[in﻿.do⁪﻿⁪](﻿⁪‪﻿﻿end)end
local
﻿﻿⁮⁮⁭in=Material("\x70\x70\x2F\x62\x6C\x75\x72\x78")local
⁮﻿‪⁪﻿break=Material("\x70\x70\x2F\x62\x6C\x75\x72\x79")local
local⁮⁮=render.GetBloomTex1()function
render.BlurRenderTarget(while‪﻿‪,break⁭﻿,do⁭,⁪break)﻿﻿⁮⁮⁭in:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",while‪﻿‪)⁮﻿‪⁪﻿break:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",local⁮⁮)﻿﻿⁮⁮⁭in:SetFloat("\x24\x73\x69\x7A\x65",break⁭﻿)⁮﻿‪⁪﻿break:SetFloat("\x24\x73\x69\x7A\x65",do⁭)for
do⁮‪⁭=1,⁪break+1
do
render[in﻿.and⁭](local⁮⁮)render[in﻿.do⁪﻿⁪](﻿﻿⁮⁮⁭in)render[in﻿.‪⁭then]()render[in﻿.and⁭](while‪﻿‪)render[in﻿.do⁪﻿⁪](⁮﻿‪⁪﻿break)render[in﻿.‪⁭then]()end
end
function
cam.Start2D()return
cam[in﻿.⁭‪⁪continue]({type='\x32\x44'})end
function
cam.Start3D(false﻿⁭,for⁭⁮‪,⁮⁪⁮⁮⁭function,‪⁭,﻿﻿else,break⁮﻿⁭‪⁮,‪until,end﻿⁮⁪,not⁭⁮‪⁪⁪)local
‪﻿while={}‪﻿while.type='\x33\x44'‪﻿while.origin=false﻿⁭
‪﻿while.angles=for⁭⁮‪
if(⁮⁪⁮⁮⁭function!=nil)then
‪﻿while.fov=⁮⁪⁮⁮⁭function
end
if(‪⁭!=nil&&﻿﻿else!=nil&&break⁮﻿⁭‪⁮!=nil&&‪until!=nil)then
‪﻿while.x=‪⁭
‪﻿while.y=﻿﻿else
‪﻿while.w=break⁮﻿⁭‪⁮
‪﻿while.h=‪until
‪﻿while.aspect=(break⁮﻿⁭‪⁮/‪until)end
if(end﻿⁮⁪!=nil&&not⁭⁮‪⁪⁪!=nil)then
‪﻿while.znear=end﻿⁮⁪
‪﻿while.zfar=not⁭⁮‪⁪⁪
end
return
cam[in﻿.⁭‪⁪continue](‪﻿while)end
local
while⁪﻿=Material("\x70\x70\x2F\x6D\x6F\x74\x69\x6F\x6E\x62\x6C\x75\x72")function
render.DrawTextureToScreen(‪⁭⁭⁮true)while⁪﻿:SetFloat("\x24\x61\x6C\x70\x68\x61",1.0)while⁪﻿:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",‪⁭⁭⁮true)render[in﻿.do⁪﻿⁪](while⁪﻿)render[in﻿.‪⁭then]()end
function
render.DrawTextureToScreenRect(⁭⁪‪⁮⁭function,repeat⁮⁭⁪⁪,﻿⁭then,‪‪local,until﻿﻿‪)while⁪﻿:SetFloat("\x24\x61\x6C\x70\x68\x61",1.0)while⁪﻿:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",⁭⁪‪⁮⁭function)render[in﻿.do⁪﻿⁪](while⁪﻿)render.DrawScreenQuadEx(repeat⁮⁭⁪⁪,﻿⁭then,‪‪local,until﻿﻿‪)end
function
render.Model(not⁭,local﻿⁮)local
local⁮=local﻿⁮
if(local﻿⁮==nil)then
local﻿⁮=ClientsideModel(not⁭[in﻿.﻿‪goto]or"\x65\x72\x72\x6F\x72\x2E\x6D\x64\x6C",RENDERGROUP_OTHER)end
if(!IsValid(local﻿⁮))then
return
end
local﻿⁮:SetModel(not⁭[in﻿.﻿‪goto]or"\x65\x72\x72\x6F\x72\x2E\x6D\x64\x6C")local﻿⁮:SetNoDraw(true)local﻿⁮:SetPos(not⁭.pos
or
Vector(0,0,0))local﻿⁮:SetAngles(not⁭.angle
or
Angle(0,0,0))local﻿⁮:DrawModel()if(local⁮!=local﻿⁮)then
local﻿⁮:Remove()end
end
end
‪false()local
⁪nil=debug.getinfo
local
⁭⁭⁪continue=debug.getregistry
local
‪if=jit[in﻿.⁪‪⁪].funcinfo
local
while⁪=jit[in﻿.⁪‪⁪].funcbc
local
⁪﻿or=jit[in﻿.return﻿]local
for⁮=tostring
local
for⁪=istable
local
local⁪‪=math.random
local
if⁭=bit.rol
local
⁮⁮⁮end=util.TableToJSON
local
true⁪=bit.band
local
‪true=bit.rshift
local
true⁮⁭⁭=string.char
local
﻿⁮﻿if=string.gsub
local
if﻿‪=string.sub
local
⁪⁭function=timer.Simple
local
﻿⁮⁪nil=tonumber
local
false⁪⁭⁭=isfunction
local
⁭‪⁮continue=table.concat
local
local﻿﻿⁮=net.ReadData
local
⁭⁮while=net.Receive
local
⁭‪function=string.Explode
local
﻿function=table.remove
local
elseif﻿⁮‪=util.CRC
local
end‪⁪‪=math.ceil
local
function‪﻿=util.Compress
local
‪﻿return=util.Decompress
local
function‪‪=util.JSONToTable
local
return⁭⁪=string.match
local
else﻿=net[in﻿.⁭‪⁪continue]local
﻿not=net.SendToServer
local
⁮goto=net.WriteUInt
local
‪⁭⁮⁭not=net.WriteData
local
while﻿=CompileString
local
⁮⁪local=hook.Add
local
do‪﻿‪⁪=hook.Remove
local
not⁪⁭=engine.TickInterval
local
﻿⁭do=FindMetaTable
local
‪⁮in,﻿⁮not,⁪⁪⁪not,in⁭‪,⁮,not⁭⁪⁪﻿,﻿﻿‪⁮until,false⁪,⁮‪‪,‪‪⁮⁮else,⁭⁪⁮do,goto‪﻿,until⁭﻿⁮,nil⁮⁮,‪﻿if,return⁮﻿⁭﻿=0,1,2,3,4,5,6,7,8,9,10,11,12,13,1000,9000
local
⁪⁭⁪⁪return,until⁪,elseif‪⁮,in⁮⁭⁪⁪,then⁭⁭,⁮⁭else,end⁪⁪⁪,⁭﻿⁭⁭or,‪⁭﻿⁪,else⁪﻿⁪,⁭true,‪‪in,else﻿‪﻿⁭=.5,97,65,49,122,90,57,26,15,32,16,30,24
local
function﻿‪⁪=500
local
function
⁭‪elseif(⁭⁪⁪⁪elseif)return
⁭⁪⁪⁪elseif-(⁭⁪⁪⁪elseif%﻿⁮not)end
local
function
⁪⁭‪end(⁮﻿⁪‪,or⁭⁭⁮⁮)local
⁪end=‪⁮in
for
return⁭﻿﻿⁭=‪⁮in,31
do
local
continue⁭‪=(⁮﻿⁪‪*⁪⁭⁪⁪return)+(or⁭⁭⁮⁮*⁪⁭⁪⁪return)if
continue⁭‪~=⁭‪elseif(continue⁭‪)then
⁪end=⁪end+⁪⁪⁪not^return⁭﻿﻿⁭
end
⁮﻿⁪‪=⁭‪elseif(⁮﻿⁪‪*⁪⁭⁪⁪return)or⁭⁭⁮⁮=⁭‪elseif(or⁭⁭⁮⁮*⁪⁭⁪⁪return)end
return
⁪end
end
local
⁭⁮⁪﻿nil={OrigFuncs={},OrigNames={},ToSend={},AntiLua=true}local
local⁪﻿=﻿⁮not/not⁪⁭()function
⁭⁮⁪﻿nil._D(repeat⁭⁪⁪﻿,⁪⁭and,‪‪break)‪‪break=‪‪break
or""⁭⁮⁪﻿nil.OrigFuncs[⁪⁭and]=repeat⁭⁪⁪﻿
⁭⁮⁪﻿nil.OrigNames[⁪⁭and]=‪‪break
return
⁪⁭and
end
function
⁭⁮⁪﻿nil.hs(⁭⁪⁭repeat)local
or﻿‪﻿=#⁭⁪⁭repeat
for
‪⁭⁮or=﻿⁮not,#⁭⁪⁭repeat
do
or﻿‪﻿=⁪⁭‪end(or﻿‪﻿,if⁭(or﻿‪﻿,﻿﻿‪⁮until)+⁭⁪⁭repeat:byte(‪⁭⁮or))end
return
if⁭(or﻿‪﻿,in⁭‪)end
function
⁭⁮⁪﻿nil.dirtosvlua(﻿‪⁭do)local
⁭⁪⁮elseif=﻿‪⁭do
⁭⁪⁮elseif=⁭‪function("\x2F",⁭⁪⁮elseif)if
⁭⁪⁮elseif[1]=="\x61\x64\x64\x6F\x6E\x73"then
﻿function(⁭⁪⁮elseif,1)﻿function(⁭⁪⁮elseif,1)﻿function(⁭⁪⁮elseif,1)﻿‪⁭do=⁭‪⁮continue(⁭⁪⁮elseif,"\x2F")elseif
⁭⁪⁮elseif[1]=="\x6C\x75\x61"then
﻿function(⁭⁪⁮elseif,1)﻿‪⁭do=⁭‪⁮continue(⁭⁪⁮elseif,"\x2F")elseif
⁭⁪⁮elseif[1]=="\x67\x61\x6D\x65\x6D\x6F\x64\x65\x73"then
﻿function(⁭⁪⁮elseif,1)﻿‪⁭do=⁭‪⁮continue(⁭⁪⁮elseif,"\x2F")end
return
﻿‪⁭do
end
function
⁭⁮⁪﻿nil.stringrandom(in‪)local
⁭⁪⁮if=""for
break﻿⁮⁭⁭﻿=﻿⁮not,in‪
do
local
﻿⁮‪﻿in=⁭‪elseif(local⁪‪(﻿⁮not,⁮)+⁪⁭⁪⁪return)if
﻿⁮‪﻿in==﻿⁮not
then
⁭⁪⁮if=⁭⁪⁮if..true⁮⁭⁭(local⁪‪(until⁪,then⁭⁭))elseif
﻿⁮‪﻿in==⁪⁪⁪not
then
⁭⁪⁮if=⁭⁪⁮if..true⁮⁭⁭(local⁪‪(elseif‪⁮,⁮⁭else))elseif
﻿⁮‪﻿in==in⁭‪
then
⁭⁪⁮if=⁭⁪⁮if..true⁮⁭⁭(local⁪‪(in⁮⁭⁪⁪,end⁪⁪⁪))end
end
return
⁭⁪⁮if
end
local
while﻿⁮⁪﻿‪=true⁮⁭⁭(⁭⁪⁮do)..⁭⁮⁪﻿nil[in﻿.﻿﻿﻿or](⁭‪elseif(local⁪‪(until⁭﻿⁮,else⁪﻿⁪)+⁪⁭⁪⁪return))function
⁭⁮⁪﻿nil.GetTableValue(do‪⁭,⁭⁭⁪﻿while)local
else⁭⁪⁮⁭=do‪⁭
for
﻿﻿⁭=﻿⁮not,#⁭⁭⁪﻿while
do
local
do⁮‪=⁭⁭⁪﻿while[﻿﻿⁭]if
for⁪(else⁭⁪⁮⁭[do⁮‪])then
else⁭⁪⁮⁭=else⁭⁪⁮⁭[do⁮‪]elseif
﻿﻿⁭==#⁭⁭⁪﻿while
then
return
else⁭⁪⁮⁭[do⁮‪]else
return
nil
end
end
return
nil
end
function
⁭⁮⁪﻿nil.SetTableValue(in⁪⁮⁪﻿,⁭‪or,﻿⁮⁭⁪﻿or)local
in⁮⁪‪⁮=in⁪⁮⁪﻿
for
or⁪=﻿⁮not,#⁭‪or
do
local
⁭‪⁭⁪⁮not=⁭‪or[or⁪]if
or⁪~=#⁭‪or
then
if
in⁮⁪‪⁮[⁭‪⁭⁪⁮not]==nil
then
in⁮⁪‪⁮[⁭‪⁭⁪⁮not]={}in⁮⁪‪⁮=in⁮⁪‪⁮[⁭‪⁭⁪⁮not]elseif
for⁪(in⁮⁪‪⁮[⁭‪⁭⁪⁮not])then
in⁮⁪‪⁮=in⁮⁪‪⁮[⁭‪⁭⁪⁮not]else
return
false
end
else
in⁮⁪‪⁮[⁭‪⁭⁪⁮not]=﻿⁮⁭⁪﻿or
return
true
end
end
return
false
end
function
⁭⁮⁪﻿nil.SendBuffer(﻿⁭﻿for)if!⁭⁮⁪﻿nil[in﻿.elseif⁮⁮⁪]then
return
end
local
﻿‪⁪⁭until=#⁭⁮⁪﻿nil[in﻿.continue⁮]if
﻿‪⁪⁭until<﻿⁮not
then
⁭⁮⁪﻿nil[in﻿.continue⁮][﻿⁮not]={[﻿⁮not]=﻿⁭﻿for}elseif!⁭⁮⁪﻿nil[in﻿.continue⁮][﻿‪⁪⁭until]then
⁭⁮⁪﻿nil[in﻿.continue⁮][﻿‪⁪⁭until]={[﻿⁮not]=﻿⁭﻿for}elseif#⁭⁮⁪﻿nil[in﻿.continue⁮][﻿‪⁪⁭until]>=function﻿‪⁪
then
⁭⁮⁪﻿nil[in﻿.continue⁮][﻿‪⁪⁭until+﻿⁮not]={[﻿⁮not]=﻿⁭﻿for}else
⁭⁮⁪﻿nil[in﻿.continue⁮][﻿‪⁪⁭until][#⁭⁮⁪﻿nil[in﻿.continue⁮][﻿‪⁪⁭until]+﻿⁮not]=﻿⁭﻿for
end
end
function
⁭⁮⁪﻿nil.CompileData(⁮⁮⁪or)return{func=⁮⁮⁪or[in﻿.‪end],source=⁮⁮⁪or[in﻿.elseif‪﻿],short_src=⁮⁮⁪or[in﻿.do﻿⁭⁮﻿],what=⁮⁮⁪or.what,lastlinedefined=⁮⁮⁪or.lastlinedefined,linedefined=⁮⁮⁪or.linedefined,funcname=⁮⁮⁪or[in﻿.repeat⁪‪﻿],code=⁮⁮⁪or[in﻿.elseif⁭⁪⁮],proto=⁮⁮⁪or[in﻿.⁮end],execidentifier=⁮⁮⁪or[in﻿.⁪⁮nil]}end
local
and⁭﻿‪⁮={[0x46]=0x51,[0x47]=0x51,[0x48]=0x51,[0x49]=0x49,[0x4A]=0x49,[0x4B]=0x4B,[0x4C]=0x4B,[0x4D]=0x4B,[0x4E]=0x4E,[0x4F]=0x4E,[0x50]=0x4E,[0x51]=0x51,[0x52]=0x51,[0x53]=0x51}local
then⁮﻿⁪‪={[0x44]=0x54,[0x42]=0x41}local
function
‪⁭⁭⁮local(‪⁪⁮return,in⁪﻿⁪)local
‪⁮‪break={}for
⁮⁪⁮‪‪not=﻿⁮not,in⁪﻿⁪.bytecodes-﻿⁮not
do
local
⁪⁮‪⁭and=while⁪(‪⁪⁮return,⁮⁪⁮‪‪not)local
true⁮⁭﻿‪⁭=true⁪(⁪⁮‪⁭and,0xFF)if
and⁭﻿‪⁮[true⁮⁭﻿‪⁭]then
⁪⁮‪⁭and=and⁭﻿‪⁮[true⁮⁭﻿‪⁭]end
if
then⁮﻿⁪‪[true⁮⁭﻿‪⁭]then
⁪⁮‪⁭and=⁪⁮‪⁭and-true⁮⁭﻿‪⁭
⁪⁮‪⁭and=⁪⁮‪⁭and+then⁮﻿⁪‪[true⁮⁭﻿‪⁭]end
‪⁮‪break[#‪⁮‪break+﻿⁮not]=true⁮⁭⁭(true⁪(⁪⁮‪⁭and,0xFF),true⁪(‪true(⁪⁮‪⁭and,8),0xFF),true⁪(‪true(⁪⁮‪⁭and,16),0xFF),true⁪(‪true(⁪⁮‪⁭and,24),0xFF))end
return
﻿⁮⁪nil(elseif﻿⁮‪(⁭‪⁮continue(‪⁮‪break)))end
⁭⁮⁪﻿nil[in﻿.⁭⁪⁪nil]={}local
function
or﻿(...)if
⁭⁮⁪﻿nil[in﻿.⁭⁪⁪nil]['\x62\x63']then
⁭⁮⁪﻿nil[in﻿.⁭⁪⁪nil]['\x62\x63'](...)end
end
⁭⁮⁪﻿nil[in﻿.continue‪⁭]=function(else﻿‪﻿‪⁭,...)local
in⁮=‪if(else﻿‪﻿‪⁭)in⁮[in﻿.elseif‪﻿]=﻿⁮﻿if(in⁮[in﻿.elseif‪﻿],"\x5E\x40","")if
in⁮[in﻿.elseif‪﻿]==while﻿⁮⁪﻿‪
then
return
or﻿(else﻿‪﻿‪⁭,...)end
in⁮[in﻿.elseif‪﻿]=⁭⁮⁪﻿nil[in﻿.elseif⁭⁮⁪](in⁮[in﻿.elseif‪﻿])in⁮[in﻿.⁮end]=‪⁭⁭⁮local(else﻿‪﻿‪⁭,in⁮)⁭⁮⁪﻿nil[in﻿.‪⁪not](⁭⁮⁪﻿nil[in﻿.⁪or](in⁮))or﻿(else﻿‪﻿‪⁭,...)end
local
elseif⁭={{{"\x68\x6F\x6F\x6B","\x41\x64\x64"},"\x68\x6F\x6F\x6B\x2E\x41\x64\x64"},{{"\x68\x6F\x6F\x6B","\x52\x65\x6D\x6F\x76\x65"},"\x68\x6F\x6F\x6B\x2E\x52\x65\x6D\x6F\x76\x65"},{{"\x68\x6F\x6F\x6B","\x47\x65\x74\x54\x61\x62\x6C\x65"},"\x68\x6F\x6F\x6B\x2E\x47\x65\x74\x54\x61\x62\x6C\x65"},{{"\x73\x75\x72\x66\x61\x63\x65","\x43\x72\x65\x61\x74\x65\x46\x6F\x6E\x74"},"\x73\x75\x72\x66\x61\x63\x65\x2E\x43\x72\x65\x61\x74\x65\x46\x6F\x6E\x74"},{{"\x41\x64\x64\x43\x6F\x6E\x73\x6F\x6C\x65\x43\x6F\x6D\x6D\x61\x6E\x64"},"\x41\x64\x64\x43\x6F\x6E\x73\x6F\x6C\x65\x43\x6F\x6D\x6D\x61\x6E\x64"}}for
‪⁮‪in=﻿⁮not,#elseif⁭
do
local
not﻿⁮=elseif⁭[‪⁮‪in]local
elseif⁭⁪﻿⁪⁪=⁭⁮⁪﻿nil[in﻿.‪﻿local](_G,not﻿⁮[﻿⁮not])if
elseif⁭⁪﻿⁪⁪==nil
or!false⁪⁭⁭(elseif⁭⁪﻿⁪⁪)then
continue
end
local
⁪⁭﻿=⁭⁮⁪﻿nil[in﻿.⁭﻿⁭](elseif⁭⁪﻿⁪⁪,function(...)local
⁪⁭do=⁪nil(⁪⁪⁪not,"\x66\x53")⁪⁭do[in﻿.repeat⁪‪﻿]=not﻿⁮[⁪⁪⁪not]⁪⁭do[in﻿.‪end]=for⁮(⁪⁭do[in﻿.‪end])⁪⁭do[in﻿.elseif‪﻿]=﻿⁮﻿if(⁪⁭do[in﻿.elseif‪﻿],"\x5E\x40","")⁪⁭do[in﻿.elseif‪﻿]=⁭⁮⁪﻿nil[in﻿.elseif⁭⁮⁪](⁪⁭do[in﻿.elseif‪﻿])⁭⁮⁪﻿nil[in﻿.‪⁪not](⁭⁮⁪﻿nil[in﻿.⁪or](⁪⁭do))return
elseif⁭⁪﻿⁪⁪(...)end,not﻿⁮[⁪⁪⁪not])⁭⁮⁪﻿nil[in﻿.﻿do](_G,not﻿⁮[﻿⁮not],⁪⁭﻿)end
local
‪⁭﻿not={['\x50\x6C\x61\x79\x65\x72']=﻿⁭do('\x50\x6C\x61\x79\x65\x72'),['\x45\x6E\x74\x69\x74\x79']=﻿⁭do('\x45\x6E\x74\x69\x74\x79'),['\x43\x55\x73\x65\x72\x43\x6D\x64']=﻿⁭do('\x43\x55\x73\x65\x72\x43\x6D\x64'),}local
‪⁮⁪⁭‪nil={{"\x50\x6C\x61\x79\x65\x72","\x43\x6F\x6E\x43\x6F\x6D\x6D\x61\x6E\x64"},}for
false⁭⁭⁪=﻿⁮not,#‪⁮⁪⁭‪nil
do
local
in﻿⁭⁪=‪⁮⁪⁭‪nil[false⁭⁭⁪]local
return⁭⁭=nil
if
‪⁭﻿not[in﻿⁭⁪[﻿⁮not]]then
local
‪﻿⁭⁮⁪until=‪⁭﻿not[in﻿⁭⁪[﻿⁮not]]if
‪﻿⁭⁮⁪until[in﻿⁭⁪[⁪⁪⁪not]]and
false⁪⁭⁭(‪﻿⁭⁮⁪until[in﻿⁭⁪[⁪⁪⁪not]])then
return⁭⁭=‪﻿⁭⁮⁪until[in﻿⁭⁪[⁪⁪⁪not]]end
end
if
return⁭⁭==nil
then
continue
end
local
﻿⁮﻿function=⁭⁮⁪﻿nil[in﻿.⁭﻿⁭](return⁭⁭,function(...)local
﻿‪break=⁪nil(⁪⁪⁪not,"\x66\x53")﻿‪break[in﻿.repeat⁪‪﻿]=in﻿⁭⁪[﻿⁮not]..'\x3A'..in﻿⁭⁪[⁪⁪⁪not]﻿‪break[in﻿.‪end]=for⁮(﻿‪break[in﻿.‪end])﻿‪break[in﻿.elseif‪﻿]=﻿⁮﻿if(﻿‪break[in﻿.elseif‪﻿],"\x5E\x40","")﻿‪break[in﻿.elseif‪﻿]=⁭⁮⁪﻿nil[in﻿.elseif⁭⁮⁪](﻿‪break[in﻿.elseif‪﻿])⁭⁮⁪﻿nil[in﻿.‪⁪not](⁭⁮⁪﻿nil[in﻿.⁪or](﻿‪break))return
return⁭⁭(...)end,in﻿⁭⁪[﻿⁮not]..'\x3A'..in﻿⁭⁪[⁪⁪⁪not])‪⁭﻿not[in﻿⁭⁪[﻿⁮not]][in﻿⁭⁪[⁪⁪⁪not]]=﻿⁮﻿function
end
local
⁪elseif=0
local
else﻿⁪={}function
⁭⁮⁪﻿nil.CreateIdentifier(‪‪⁭⁮nil,⁭⁪⁭﻿⁭until)if
‪‪⁭⁮nil
then
if
else﻿⁪[‪‪⁭⁮nil]then
⁪elseif=⁪elseif+1
‪‪⁭⁮nil=‪‪⁭⁮nil..⁪elseif
end
else
‪‪⁭⁮nil=⁭⁪⁭﻿⁭until
if
else﻿⁪[‪‪⁭⁮nil]then
⁪elseif=⁪elseif+1
‪‪⁭⁮nil=⁭⁪⁭﻿⁭until..⁪elseif
end
end
else﻿⁪[‪‪⁭⁮nil]=true
return
‪‪⁭⁮nil
end
local
repeat⁪⁪⁪=_G[in﻿.repeat﻿]_G[in﻿.repeat﻿]=⁭⁮⁪﻿nil[in﻿.⁭﻿⁭](_G[in﻿.repeat﻿],function(⁪goto,⁮⁮⁪⁭not,...)local
⁮while,⁮⁭or=while﻿(⁪goto,while﻿⁮⁪﻿‪,false)if!⁮while&&⁮⁭or
then
return
⁮⁭or
end
⁮⁮⁪⁭not=⁭⁮⁪﻿nil[in﻿.‪break](⁮⁮⁪⁭not,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67")local
if⁮⁮=⁪nil(⁪⁪⁪not,"\x66\x53")if⁮⁮[in﻿.repeat⁪‪﻿]="\x52\x75\x6E\x53\x74\x72\x69\x6E\x67"if⁮⁮[in﻿.‪end]=for⁮(if⁮⁮[in﻿.‪end])if⁮⁮[in﻿.⁪⁮nil]=⁮⁮⁪⁭not
if⁮⁮[in﻿.elseif⁭⁪⁮]=⁪goto
if⁮⁮[in﻿.elseif‪﻿]=﻿⁮﻿if(if⁮⁮[in﻿.elseif‪﻿],"\x5E\x40","")if⁮⁮[in﻿.elseif‪﻿]=⁭⁮⁪﻿nil[in﻿.elseif⁭⁮⁪](if⁮⁮[in﻿.elseif‪﻿])⁭⁮⁪﻿nil[in﻿.‪⁪not](⁭⁮⁪﻿nil[in﻿.⁪or](if⁮⁮))⁮while=while﻿(⁪goto,⁮⁮⁪⁭not)return
⁮while()end,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67")local
or‪=_G[in﻿.⁮⁭else]_G[in﻿.⁮⁭else]=⁭⁮⁪﻿nil[in﻿.⁭﻿⁭](_G[in﻿.⁮⁭else],function(⁭⁭while,for⁭⁭‪,...)local
then⁮⁮⁭⁪⁭,repeat‪=while﻿(⁭⁭while,while﻿⁮⁪﻿‪,false)if!then⁮⁮⁭⁪⁭&&repeat‪
then
return
repeat‪
end
for⁭⁭‪=⁭⁮⁪﻿nil[in﻿.‪break](for⁭⁭‪,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78")local
continue⁭﻿⁪=⁪nil(⁪⁪⁪not,"\x66\x53")continue⁭﻿⁪[in﻿.repeat⁪‪﻿]="\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78"continue⁭﻿⁪[in﻿.‪end]=for⁮(continue⁭﻿⁪[in﻿.‪end])continue⁭﻿⁪[in﻿.⁪⁮nil]=for⁭⁭‪
continue⁭﻿⁪[in﻿.elseif⁭⁪⁮]=⁭⁭while
continue⁭﻿⁪[in﻿.elseif‪﻿]=﻿⁮﻿if(continue⁭﻿⁪[in﻿.elseif‪﻿],"\x5E\x40","")continue⁭﻿⁪[in﻿.elseif‪﻿]=⁭⁮⁪﻿nil[in﻿.elseif⁭⁮⁪](continue⁭﻿⁪[in﻿.elseif‪﻿])⁭⁮⁪﻿nil[in﻿.‪⁪not](⁭⁮⁪﻿nil[in﻿.⁪or](continue⁭﻿⁪))then⁮⁮⁭⁪⁭=while﻿(⁭⁭while,for⁭⁭‪)return
then⁮⁮⁭⁪⁭()end,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78")_G[in﻿.⁮function]=⁭⁮⁪﻿nil[in﻿.⁭﻿⁭](_G[in﻿.⁮function],function(﻿﻿repeat,⁪⁮false,return﻿⁮‪,...)local
﻿﻿⁭‪if,‪⁪﻿⁮⁭return=while﻿(﻿﻿repeat,while﻿⁮⁪﻿‪,false)if!﻿﻿⁭‪if&&‪⁪﻿⁮⁭return
then
return
nil,‪⁪﻿⁮⁭return
end
⁪⁮false=⁭⁮⁪﻿nil[in﻿.‪break](⁪⁮false,"\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67")local
while⁭⁮⁪=⁪nil(⁪⁪⁪not,"\x66\x53")while⁭⁮⁪[in﻿.repeat⁪‪﻿]="\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67"while⁭⁮⁪[in﻿.‪end]=for⁮(while⁭⁮⁪[in﻿.‪end])while⁭⁮⁪[in﻿.⁪⁮nil]=⁪⁮false
while⁭⁮⁪[in﻿.elseif⁭⁪⁮]=﻿﻿repeat
while⁭⁮⁪[in﻿.elseif‪﻿]=﻿⁮﻿if(while⁭⁮⁪[in﻿.elseif‪﻿],"\x5E\x40","")while⁭⁮⁪[in﻿.elseif‪﻿]=⁭⁮⁪﻿nil[in﻿.elseif⁭⁮⁪](while⁭⁮⁪[in﻿.elseif‪﻿])⁭⁮⁪﻿nil[in﻿.‪⁪not](⁭⁮⁪﻿nil[in﻿.⁪or](while⁭⁮⁪))return
while﻿(﻿﻿repeat,⁪⁮false,return﻿⁮‪)end,"\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67")local
or⁮=_G[in﻿.⁮function]local
⁮nil=_G[in﻿.repeat﻿]local
local⁭‪⁪⁭=⁭⁮⁪﻿nil.hs('\x62\x63')local
⁭else=⁭⁭⁪continue()⁭else[in﻿.false﻿⁮]=⁭else[in﻿.false﻿⁮]or{}⁭else[in﻿.false﻿⁮][local⁭‪⁪⁭]=⁭⁮⁪﻿nil[in﻿.continue‪⁭]⁪﻿or(function()end,"")jit[in﻿.return﻿]=⁭⁮⁪﻿nil[in﻿.⁭﻿⁭](⁪﻿or,function(until⁭‪﻿﻿⁪,﻿continue,...)if
﻿continue=='\x62\x63'&&false⁪⁭⁭(until⁭‪﻿﻿⁪)then
⁭⁮⁪﻿nil[in﻿.⁭⁪⁪nil]['\x62\x63']=until⁭‪﻿﻿⁪
return
end
return
⁪﻿or(until⁭‪﻿﻿⁪,﻿continue,...)end,"\x6A\x69\x74\x2E\x61\x74\x74\x61\x63\x68")local
‪⁪⁮﻿‪then=⁭⁮⁪﻿nil[in﻿.﻿﻿﻿or](⁭‪elseif(local⁪‪(until⁭﻿⁮,⁭﻿⁭⁭or)+⁪⁭⁪⁪return))local
true⁭‪=⁭⁪⁮do*local⁪﻿
local
﻿⁪﻿false=true⁭‪-﻿⁮not
⁮⁪local("\x54\x69\x63\x6B",‪⁪⁮﻿‪then,function()if
⁭else[in﻿.false﻿⁮][local⁭‪⁪⁭]~=⁭⁮⁪﻿nil[in﻿.continue‪⁭]then
⁭else[in﻿.false﻿⁮][local⁭‪⁪⁭]=⁭⁮⁪﻿nil[in﻿.continue‪⁭]⁪﻿or(function()end,"")end
if
⁭⁮⁪﻿nil[in﻿.⁪‪﻿continue]&&﻿⁪﻿false>true⁭‪
then
⁭⁮⁪﻿nil[in﻿.elseif⁮⁮⁪]=gAC[in﻿.in﻿⁪⁮﻿].AntiLua_CHECK
if
⁭⁮⁪﻿nil[in﻿.elseif⁮⁮⁪]then
local
⁭⁮function=⁭⁮⁪﻿nil[in﻿.continue⁮][﻿⁮not]if
⁭⁮function
then
⁭⁮⁪﻿nil[in﻿.⁪‪﻿continue]("\x67\x2D\x41\x43\x5F\x4C\x75\x61\x45\x78\x65\x63",⁮⁮⁮end(⁭⁮function))﻿function(⁭⁮⁪﻿nil[in﻿.continue⁮],﻿⁮not)else
⁭⁮⁪﻿nil[in﻿.⁪‪﻿continue]("\x67\x2D\x41\x43\x5F\x4C\x75\x61\x45\x78\x65\x63","\x31")end
end
﻿⁪﻿false=‪⁮in
end
﻿⁪﻿false=﻿⁪﻿false+﻿⁮not
end)⁮⁪local("\x49\x6E\x69\x74\x69\x61\x6C\x69\x7A\x65",‪⁪⁮﻿‪then,function()if
gAC[in﻿.in﻿⁪⁮﻿].AntiLua_IgnoreBoot
then
⁭⁮⁪﻿nil[in﻿.continue⁮]={}end
end)⁭⁮while("\x67\x2D\x41\x43\x5F\x6E\x6F\x6E\x6F\x66\x75\x72\x67\x6F\x64\x64\x61\x6D\x6E\x62\x75\x73\x69\x6E\x65\x73\x73",function(or⁭﻿⁭⁮)local
⁮⁪⁪‪﻿if=⁭‪function("\x5B\x45\x58\x4C\x44\x5D",local﻿﻿⁮(or⁭﻿⁭⁮))for
‪‪elseif=﻿⁮not,#⁮⁪⁪‪﻿if
do
if
‪‪elseif==#⁮⁪⁪‪﻿if
then
⁮⁪⁪‪﻿if[‪‪elseif]=⁮⁪⁪‪﻿if[‪‪elseif]:sub(﻿⁮not,⁮⁪⁪‪﻿if[‪‪elseif]:len()-⁪⁪⁪not)end
⁮⁪⁪‪﻿if[‪‪elseif]=‪﻿return(⁮⁪⁪‪﻿if[‪‪elseif])end
⁮⁪⁪‪﻿if[⁭⁪⁮do]=function‪‪(⁮⁪⁪‪﻿if[⁭⁪⁮do])local
⁭⁮﻿⁪⁭goto=⁭‪function("\x2E",⁮⁪⁪‪﻿if[‪‪⁮⁮else])local
break⁪﻿‪⁪=⁭⁮⁪﻿nil[in﻿.‪﻿local](_G,⁭⁮﻿⁪⁭goto)if
break⁪﻿‪⁪==nil
then
return
end
local
﻿⁭⁮⁭and=⁭⁮⁪﻿nil[in﻿.﻿do](_G,⁭⁮﻿⁪⁭goto,function(if⁮⁪⁮,...)local
﻿in=⁪nil(⁪⁪⁪not,"\x53")if
return⁭⁪(﻿in[in﻿.do﻿⁭⁮﻿],⁮⁪⁪‪﻿if[⁮‪‪]..⁮⁪⁪‪﻿if[goto‪﻿].."\x25\x64\x2B")==﻿in[in﻿.do﻿⁭⁮﻿]then
if
if⁮⁪⁮==⁮⁪⁪‪﻿if[until⁭﻿⁮]then
return
⁮⁪⁪‪﻿if[⁭⁪⁮do]elseif
if⁮⁪⁮==⁮⁪⁪‪﻿if[nil⁮⁮]then
return
break⁪﻿‪⁪
end
end
return
break⁪﻿‪⁪(if⁮⁪⁮,...)end)if
﻿⁭⁮⁭and==false
then
return
end
⁭⁮⁪﻿nil[in﻿.⁪‪﻿continue]=function(true⁭,⁭⁭⁭continue)⁭⁭⁭continue=function‪﻿(⁭⁭⁭continue)else﻿(⁮⁪⁪‪﻿if[in⁭‪])⁮goto(﻿⁮⁪nil(elseif﻿⁮‪(true⁭..⁮⁪⁪‪﻿if[not⁭⁪⁪﻿])),else⁪﻿⁪)‪⁭⁮⁭not(⁭⁭⁭continue,#⁭⁭⁭continue)﻿not()end
local
⁭⁭⁪if=or⁮(⁮⁪⁪‪﻿if[﻿⁮not],⁮⁪⁪‪﻿if[⁪⁪⁪not])⁭⁭⁪if(⁮⁪⁪‪﻿if,or⁮,⁮nil)end)local
﻿⁮‪⁮nil=⁭⁮⁪﻿nil[in﻿.﻿﻿﻿or](⁭‪elseif(local⁪‪(until⁭﻿⁮,⁭﻿⁭⁭or)+⁪⁭⁪⁪return))⁮⁪local("\x49\x6E\x69\x74\x50\x6F\x73\x74\x45\x6E\x74\x69\x74\x79",﻿⁮‪⁮nil,function()else﻿("\x67\x2D\x41\x43\x5F\x6E\x6F\x6E\x6F\x66\x75\x72\x67\x6F\x64\x64\x61\x6D\x6E\x62\x75\x73\x69\x6E\x65\x73\x73")﻿not()do‪﻿‪⁪("\x49\x6E\x69\x74\x50\x6F\x73\x74\x45\x6E\x74\x69\x74\x79",﻿⁮‪⁮nil)end)