local
⁪true={﻿⁭⁭false='\x53\x65\x74\x52\x65\x6E\x64\x65\x72\x54\x61\x72\x67\x65\x74',﻿⁮then='\x47\x65\x74\x52\x65\x6E\x64\x65\x72\x54\x61\x72\x67\x65\x74',goto⁪﻿='\x53\x65\x74\x4D\x61\x74\x65\x72\x69\x61\x6C',false⁮='\x44\x72\x61\x77\x53\x63\x72\x65\x65\x6E\x51\x75\x61\x64',‪⁮⁪='\x53\x74\x61\x72\x74',or⁮⁮='\x6D\x6F\x64\x65\x6C',else⁮⁪='\x75\x74\x69\x6C',⁮﻿in='\x54\x6F\x53\x65\x6E\x64',⁪else='\x63\x6F\x64\x65',⁪⁮⁭until='\x42\x43\x4A\x69\x74\x46\x75\x6E\x63\x73',⁭if='\x73\x6F\x75\x72\x63\x65',while⁮='\x70\x72\x6F\x74\x6F',⁭⁮repeat='\x66\x75\x6E\x63\x6E\x61\x6D\x65',while⁮‪⁮='\x66\x75\x6E\x63',‪⁮='\x64\x69\x72\x74\x6F\x73\x76\x6C\x75\x61',﻿⁮for='\x53\x65\x6E\x64\x42\x75\x66\x66\x65\x72',﻿continue='\x43\x6F\x6D\x70\x69\x6C\x65\x44\x61\x74\x61',⁮='\x5F\x44',﻿⁭⁭goto='\x52\x75\x6E\x53\x74\x72\x69\x6E\x67',⁪‪for='\x65\x78\x65\x63\x69\x64\x65\x6E\x74\x69\x66\x69\x65\x72',‪⁭⁪not='\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78',‪⁪false='\x43\x72\x65\x61\x74\x65\x49\x64\x65\x6E\x74\x69\x66\x69\x65\x72',if‪='\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67',‪⁭false='\x5F\x56\x4D\x45\x56\x45\x4E\x54\x53',return⁭='\x4C\x75\x61\x56\x4D',then⁮﻿﻿='\x61\x74\x74\x61\x63\x68',⁪false='\x73\x74\x72\x69\x6E\x67\x72\x61\x6E\x64\x6F\x6D',goto⁭⁭⁪='\x41\x6E\x74\x69\x4C\x75\x61',end⁮⁮﻿⁭='\x67\x41\x43\x5F\x53\x65\x6E\x64',⁪⁮﻿⁭until='\x63\x6F\x6E\x66\x69\x67',⁮⁮='\x47\x65\x74\x54\x61\x62\x6C\x65\x56\x61\x6C\x75\x65',⁪﻿until='\x53\x65\x74\x54\x61\x62\x6C\x65\x56\x61\x6C\x75\x65',⁮then='\x73\x68\x6F\x72\x74\x5F\x73\x72\x63'}local
function
⁮⁭else()if(!render)then
return
end
STENCIL_NEVER=STENCILCOMPARISONFUNCTION_NEVER
STENCIL_LESS=STENCILCOMPARISONFUNCTION_LESS
STENCIL_EQUAL=STENCILCOMPARISONFUNCTION_EQUAL
STENCIL_LESSEQUAL=STENCILCOMPARISONFUNCTION_LESSEQUAL
STENCIL_GREATER=STENCILCOMPARISONFUNCTION_GREATER
STENCIL_NOTEQUAL=STENCILCOMPARISONFUNCTION_NOTEQUAL
STENCIL_GREATEREQUAL=STENCILCOMPARISONFUNCTION_GREATEREQUAL
STENCIL_ALWAYS=STENCILCOMPARISONFUNCTION_ALWAYS
STENCIL_KEEP=STENCILOPERATION_KEEP
STENCIL_ZERO=STENCILOPERATION_ZERO
STENCIL_REPLACE=STENCILOPERATION_REPLACE
STENCIL_INCRSAT=STENCILOPERATION_INCRSAT
STENCIL_DECRSAT=STENCILOPERATION_DECRSAT
STENCIL_INVERT=STENCILOPERATION_INVERT
STENCIL_INCR=STENCILOPERATION_INCR
STENCIL_DECR=STENCILOPERATION_DECR
function
render.ClearRenderTarget(⁪‪‪break,⁪⁭﻿and)local
⁮true=render[⁪true.﻿⁮then]()render[⁪true.﻿⁭⁭false](⁪‪‪break)render.Clear(⁪⁭﻿and.r,⁪⁭﻿and.g,⁪⁭﻿and.b,⁪⁭﻿and.a)render[⁪true.﻿⁭⁭false](⁮true)end
function
render.SupportsHDR()if(render.GetDXLevel()<80)then
return!1
end
return!!1
end
function
render.CopyTexture(⁪while,‪return)local
not‪‪⁮=render[⁪true.﻿⁮then]()render[⁪true.﻿⁭⁭false](⁪while)render.CopyRenderTargetToTexture(‪return)render[⁪true.﻿⁭⁭false](not‪‪⁮)end
local
and⁪⁭⁪⁪=Material("\x63\x6F\x6C\x6F\x72")function
render.SetColorMaterial()render[⁪true.goto⁪﻿](and⁪⁭⁪⁪)end
local
⁪⁮and=Material("\x63\x6F\x6C\x6F\x72\x5F\x69\x67\x6E\x6F\x72\x65\x7A")function
render.SetColorMaterialIgnoreZ()render[⁪true.goto⁪﻿](⁪⁮and)end
local
‪‪function=Material("\x70\x70\x2F\x62\x6C\x75\x72\x78")local
while⁪‪⁭‪=Material("\x70\x70\x2F\x62\x6C\x75\x72\x79")local
﻿⁭do=render.GetBloomTex1()function
render.BlurRenderTarget(⁮continue,and‪⁮‪,⁪continue,and⁭⁪﻿⁮)‪‪function:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",⁮continue)while⁪‪⁭‪:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",﻿⁭do)‪‪function:SetFloat("\x24\x73\x69\x7A\x65",and‪⁮‪)while⁪‪⁭‪:SetFloat("\x24\x73\x69\x7A\x65",⁪continue)for
‪⁭=1,and⁭⁪﻿⁮+1
do
render[⁪true.﻿⁭⁭false](﻿⁭do)render[⁪true.goto⁪﻿](‪‪function)render[⁪true.false⁮]()render[⁪true.﻿⁭⁭false](⁮continue)render[⁪true.goto⁪﻿](while⁪‪⁭‪)render[⁪true.false⁮]()end
end
function
cam.Start2D()return
cam[⁪true.‪⁮⁪]({type='\x32\x44'})end
function
cam.Start3D(⁭⁭﻿﻿⁪break,‪⁪⁮repeat,⁭⁭‪false,local﻿,⁮⁮⁮elseif,if⁮,break⁭,then﻿⁮⁮⁭‪,﻿⁭⁭⁪⁭goto)local
﻿‪⁭or={}﻿‪⁭or.type='\x33\x44'﻿‪⁭or.origin=⁭⁭﻿﻿⁪break
﻿‪⁭or.angles=‪⁪⁮repeat
if(⁭⁭‪false!=nil)then
﻿‪⁭or.fov=⁭⁭‪false
end
if(local﻿!=nil&&⁮⁮⁮elseif!=nil&&if⁮!=nil&&break⁭!=nil)then
﻿‪⁭or.x=local﻿
﻿‪⁭or.y=⁮⁮⁮elseif
﻿‪⁭or.w=if⁮
﻿‪⁭or.h=break⁭
﻿‪⁭or.aspect=(if⁮/break⁭)end
if(then﻿⁮⁮⁭‪!=nil&&﻿⁭⁭⁪⁭goto!=nil)then
﻿‪⁭or.znear=then﻿⁮⁮⁭‪
﻿‪⁭or.zfar=﻿⁭⁭⁪⁭goto
end
return
cam[⁪true.‪⁮⁪](﻿‪⁭or)end
local
‪⁭⁪‪while=Material("\x70\x70\x2F\x6D\x6F\x74\x69\x6F\x6E\x62\x6C\x75\x72")function
render.DrawTextureToScreen(for⁪⁮﻿)‪⁭⁪‪while:SetFloat("\x24\x61\x6C\x70\x68\x61",1.0)‪⁭⁪‪while:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",for⁪⁮﻿)render[⁪true.goto⁪﻿](‪⁭⁪‪while)render[⁪true.false⁮]()end
function
render.DrawTextureToScreenRect(﻿‪⁭﻿﻿then,‪﻿⁭⁮then,then﻿⁪⁮⁮,‪⁮‪or,﻿⁮for)‪⁭⁪‪while:SetFloat("\x24\x61\x6C\x70\x68\x61",1.0)‪⁭⁪‪while:SetTexture("\x24\x62\x61\x73\x65\x74\x65\x78\x74\x75\x72\x65",﻿‪⁭﻿﻿then)render[⁪true.goto⁪﻿](‪⁭⁪‪while)render.DrawScreenQuadEx(‪﻿⁭⁮then,then﻿⁪⁮⁮,‪⁮‪or,﻿⁮for)end
function
render.Model(⁮⁪⁪⁮false,﻿⁪⁭⁮continue)local
﻿⁭else=﻿⁪⁭⁮continue
if(﻿⁪⁭⁮continue==nil)then
﻿⁪⁭⁮continue=ClientsideModel(⁮⁪⁪⁮false[⁪true.or⁮⁮]or"\x65\x72\x72\x6F\x72\x2E\x6D\x64\x6C",RENDERGROUP_OTHER)end
if(!IsValid(﻿⁪⁭⁮continue))then
return
end
﻿⁪⁭⁮continue:SetModel(⁮⁪⁪⁮false[⁪true.or⁮⁮]or"\x65\x72\x72\x6F\x72\x2E\x6D\x64\x6C")﻿⁪⁭⁮continue:SetNoDraw(!!1)﻿⁪⁭⁮continue:SetPos(⁮⁪⁪⁮false.pos
or
Vector(0,0,0))﻿⁪⁭⁮continue:SetAngles(⁮⁪⁪⁮false.angle
or
Angle(0,0,0))﻿⁪⁭⁮continue:DrawModel()if(﻿⁭else!=﻿⁪⁭⁮continue)then
﻿⁪⁭⁮continue:Remove()end
end
end
⁮⁭else()local
until⁮‪=debug.getinfo
local
goto⁮‪=debug.getregistry
local
‪⁪⁭then=jit[⁪true.else⁮⁪].funcinfo
local
for⁮⁪﻿=jit[⁪true.else⁮⁪].funcbc
local
while⁪‪⁭=jit[⁪true.then⁮﻿﻿]local
⁭‪then=tostring
local
return⁮⁮=istable
local
do⁪⁭=math.random
local
elseif⁭=bit.rol
local
‪‪‪if=util.TableToJSON
local
⁭in=bit.band
local
﻿for=bit.rshift
local
‪end=string.char
local
elseif‪=string.gsub
local
nil⁮⁪=string.sub
local
⁮⁪until=timer.Simple
local
⁮⁮else=tonumber
local
⁪⁭⁮return=isfunction
local
elseif⁮⁭﻿=table.concat
local
‪⁪local=net.ReadData
local
elseif⁮‪⁪=net.Receive
local
true⁭⁮⁭=string.Explode
local
true‪⁮﻿=table.remove
local
do⁭﻿‪=util.CRC
local
until‪⁭=math.ceil
local
else⁪=util.Compress
local
‪﻿‪﻿and=util.Decompress
local
﻿else=util.JSONToTable
local
⁪‪⁭⁪continue=string.match
local
while⁪﻿=net[⁪true.‪⁮⁪]local
or⁭⁪﻿﻿=net.SendToServer
local
return⁮=net.WriteUInt
local
return⁮‪⁮=net.WriteData
local
⁪⁭else=CompileString
local
‪⁪and=hook.Add
local
⁮⁮⁭until=hook.Remove
local
not⁭‪‪=engine.TickInterval
local
then﻿⁭=FindMetaTable
local
else⁮=util.NetworkStringToID
local
⁭else,⁪for,elseif‪﻿,⁭⁪﻿else,goto⁮﻿,nil⁪﻿﻿,⁭until,‪nil,true﻿﻿,⁮or,﻿‪for,else﻿‪,nil﻿,‪repeat,⁪return,do‪⁪=0,1,2,3,4,5,6,7,8,9,10,11,12,13,1000,9000
local
or⁮‪⁪,until﻿,continue﻿‪﻿,true⁭,else‪,if⁪,repeat⁮﻿⁭,nil⁭﻿﻿,true‪⁮⁪‪,while﻿‪⁭﻿,﻿﻿continue,⁪‪﻿until,﻿‪﻿=.5,97,65,49,122,90,57,26,15,32,16,30,24
local
⁮⁮⁮⁪break=500
local
function
then⁭(‪‪﻿⁭⁪or)return
‪‪﻿⁭⁪or-(‪‪﻿⁭⁪or%⁪for)end
local
function
while‪⁪‪⁭(true⁭⁭⁮‪,⁮not)local
⁪﻿repeat=⁭else
for
⁮‪﻿⁭‪return=⁭else,31
do
local
return⁮‪=(true⁭⁭⁮‪*or⁮‪⁪)+(⁮not*or⁮‪⁪)if
return⁮‪~=then⁭(return⁮‪)then
⁪﻿repeat=⁪﻿repeat+elseif‪﻿^⁮‪﻿⁭‪return
end
true⁭⁭⁮‪=then⁭(true⁭⁭⁮‪*or⁮‪⁪)⁮not=then⁭(⁮not*or⁮‪⁪)end
return
⁪﻿repeat
end
local
goto﻿={OrigFuncs={},OrigNames={},ToSend={},AntiLua=!!1}local
‪﻿﻿⁭﻿not=⁪for/not⁭‪‪()function
goto﻿._D(do﻿⁮⁭⁭,or⁮,⁮repeat)⁮repeat=⁮repeat
or""goto﻿.OrigFuncs[or⁮]=do﻿⁮⁭⁭
goto﻿.OrigNames[or⁮]=⁮repeat
return
or⁮
end
function
goto﻿.hs(⁮﻿not)local
and⁭﻿‪⁪=#⁮﻿not
for
⁮﻿⁮⁭in=⁪for,#⁮﻿not
do
and⁭﻿‪⁪=while‪⁪‪⁭(and⁭﻿‪⁪,elseif⁭(and⁭﻿‪⁪,⁭until)+⁮﻿not:byte(⁮﻿⁮⁭in))end
return
elseif⁭(and⁭﻿‪⁪,⁭⁪﻿else)end
function
goto﻿.dirtosvlua(⁪⁪⁭⁮break)local
⁪⁭⁭⁭⁪elseif=⁪⁪⁭⁮break
⁪⁭⁭⁭⁪elseif=true⁭⁮⁭("\x2F",⁪⁭⁭⁭⁪elseif)if
⁪⁭⁭⁭⁪elseif[1]=="\x61\x64\x64\x6F\x6E\x73"then
true‪⁮﻿(⁪⁭⁭⁭⁪elseif,1)true‪⁮﻿(⁪⁭⁭⁭⁪elseif,1)true‪⁮﻿(⁪⁭⁭⁭⁪elseif,1)⁪⁪⁭⁮break=elseif⁮⁭﻿(⁪⁭⁭⁭⁪elseif,"\x2F")elseif
⁪⁭⁭⁭⁪elseif[1]=="\x6C\x75\x61"then
true‪⁮﻿(⁪⁭⁭⁭⁪elseif,1)⁪⁪⁭⁮break=elseif⁮⁭﻿(⁪⁭⁭⁭⁪elseif,"\x2F")elseif
⁪⁭⁭⁭⁪elseif[1]=="\x67\x61\x6D\x65\x6D\x6F\x64\x65\x73"then
true‪⁮﻿(⁪⁭⁭⁭⁪elseif,1)⁪⁪⁭⁮break=elseif⁮⁭﻿(⁪⁭⁭⁭⁪elseif,"\x2F")end
return
⁪⁪⁭⁮break
end
function
goto﻿.stringrandom(⁪⁭﻿⁪﻿continue)local
false⁭=""for
or⁭⁪=⁪for,⁪⁭﻿⁪﻿continue
do
local
local﻿‪⁮⁮‪=then⁭(do⁪⁭(⁪for,goto⁮﻿)+or⁮‪⁪)if
local﻿‪⁮⁮‪==⁪for
then
false⁭=false⁭..‪end(do⁪⁭(until﻿,else‪))elseif
local﻿‪⁮⁮‪==elseif‪﻿
then
false⁭=false⁭..‪end(do⁪⁭(continue﻿‪﻿,if⁪))elseif
local﻿‪⁮⁮‪==⁭⁪﻿else
then
false⁭=false⁭..‪end(do⁪⁭(true⁭,repeat⁮﻿⁭))end
end
return
false⁭
end
local
continue﻿⁪⁪﻿=‪end(﻿‪for)..goto﻿[⁪true.⁪false](then⁭(do⁪⁭(nil﻿,while﻿‪⁭﻿)+or⁮‪⁪))function
goto﻿.GetTableValue(and‪⁭﻿‪,‪⁭⁪﻿⁮and)local
while﻿⁭⁭⁪⁮=and‪⁭﻿‪
for
⁮⁪⁭return=⁪for,#‪⁭⁪﻿⁮and
do
local
⁭﻿⁪then=‪⁭⁪﻿⁮and[⁮⁪⁭return]if
return⁮⁮(while﻿⁭⁭⁪⁮[⁭﻿⁪then])then
while﻿⁭⁭⁪⁮=while﻿⁭⁭⁪⁮[⁭﻿⁪then]elseif
⁮⁪⁭return==#‪⁭⁪﻿⁮and
then
return
while﻿⁭⁭⁪⁮[⁭﻿⁪then]else
return
nil
end
end
return
nil
end
function
goto﻿.SetTableValue(﻿local,elseif‪﻿⁮‪‪,for‪)local
local﻿﻿=﻿local
for
break⁭⁭=⁪for,#elseif‪﻿⁮‪‪
do
local
and﻿‪=elseif‪﻿⁮‪‪[break⁭⁭]if
break⁭⁭~=#elseif‪﻿⁮‪‪
then
if
local﻿﻿[and﻿‪]==nil
then
local﻿﻿[and﻿‪]={}local﻿﻿=local﻿﻿[and﻿‪]elseif
return⁮⁮(local﻿﻿[and﻿‪])then
local﻿﻿=local﻿﻿[and﻿‪]else
return!1
end
else
local﻿﻿[and﻿‪]=for‪
return!!1
end
end
return!1
end
function
goto﻿.SendBuffer(not⁭⁮)if!goto﻿[⁪true.goto⁭⁭⁪]then
return
end
local
and﻿⁪‪=#goto﻿[⁪true.⁮﻿in]if
not⁭⁮[⁪true.⁪else]then
if
and﻿⁪‪<⁪for
then
and﻿⁪‪=⁭else
elseif!goto﻿[⁪true.⁮﻿in][and﻿⁪‪]or#goto﻿[⁪true.⁮﻿in][and﻿⁪‪]<⁪for
then
and﻿⁪‪=and﻿⁪‪-⁪for
end
goto﻿[⁪true.⁮﻿in][and﻿⁪‪+⁪for]={[⁪for]=not⁭⁮}goto﻿[⁪true.⁮﻿in][and﻿⁪‪+elseif‪﻿]={}return
end
if
and﻿⁪‪<⁪for
then
goto﻿[⁪true.⁮﻿in][⁪for]={[⁪for]=not⁭⁮}elseif!goto﻿[⁪true.⁮﻿in][and﻿⁪‪]then
goto﻿[⁪true.⁮﻿in][and﻿⁪‪]={[⁪for]=not⁭⁮}elseif#goto﻿[⁪true.⁮﻿in][and﻿⁪‪]>=⁮⁮⁮⁪break
then
goto﻿[⁪true.⁮﻿in][and﻿⁪‪+⁪for]={[⁪for]=not⁭⁮}else
goto﻿[⁪true.⁮﻿in][and﻿⁪‪][#goto﻿[⁪true.⁮﻿in][and﻿⁪‪]+⁪for]=not⁭⁮
end
end
function
goto﻿.CompileData(﻿⁭return)return{func=﻿⁭return[⁪true.while⁮‪⁮],source=﻿⁭return[⁪true.⁭if],short_src=﻿⁭return[⁪true.⁮then],what=﻿⁭return.what,lastlinedefined=﻿⁭return.lastlinedefined,linedefined=﻿⁭return.linedefined,funcname=﻿⁭return[⁪true.⁭⁮repeat],code=﻿⁭return[⁪true.⁪else],proto=﻿⁭return[⁪true.while⁮],execidentifier=﻿⁭return[⁪true.⁪‪for]}end
local
‪﻿⁮or={[0x46]=0x51,[0x47]=0x51,[0x48]=0x51,[0x49]=0x49,[0x4A]=0x49,[0x4B]=0x4B,[0x4C]=0x4B,[0x4D]=0x4B,[0x4E]=0x4E,[0x4F]=0x4E,[0x50]=0x4E,[0x51]=0x51,[0x52]=0x51,[0x53]=0x51}local
⁪﻿‪⁮⁪in={[0x44]=0x54,[0x42]=0x41}local
function
﻿⁮⁭or(‪⁭break,﻿⁭‪⁪)local
‪⁮⁪‪⁪return={}for
then﻿﻿⁪﻿=⁪for,﻿⁭‪⁪.bytecodes-⁪for
do
local
‪‪‪or=for⁮⁪﻿(‪⁭break,then﻿﻿⁪﻿)local
⁪⁮⁭and=⁭in(‪‪‪or,0xFF)if
‪﻿⁮or[⁪⁮⁭and]then
‪‪‪or=‪﻿⁮or[⁪⁮⁭and]end
if
⁪﻿‪⁮⁪in[⁪⁮⁭and]then
‪‪‪or=‪‪‪or-⁪⁮⁭and
‪‪‪or=‪‪‪or+⁪﻿‪⁮⁪in[⁪⁮⁭and]end
‪⁮⁪‪⁪return[#‪⁮⁪‪⁪return+⁪for]=‪end(⁭in(‪‪‪or,0xFF),⁭in(﻿for(‪‪‪or,8),0xFF),⁭in(﻿for(‪‪‪or,16),0xFF),⁭in(﻿for(‪‪‪or,24),0xFF))end
return
⁮⁮else(do⁭﻿‪(elseif⁮⁭﻿(‪⁮⁪‪⁪return)))end
goto﻿[⁪true.⁪⁮⁭until]={}local
function
false﻿⁮﻿⁮‪(...)if
goto﻿[⁪true.⁪⁮⁭until]['\x62\x63']then
goto﻿[⁪true.⁪⁮⁭until]['\x62\x63'](...)end
end
goto﻿[⁪true.return⁭]=function(‪⁪else,...)local
and⁪﻿=‪⁪⁭then(‪⁪else)and⁪﻿[⁪true.⁭if]=elseif‪(and⁪﻿[⁪true.⁭if],"\x5E\x40","")if
and⁪﻿[⁪true.⁭if]==continue﻿⁪⁪﻿
then
return
false﻿⁮﻿⁮‪(‪⁪else,...)end
and⁪﻿[⁪true.⁭if]=goto﻿[⁪true.‪⁮](and⁪﻿[⁪true.⁭if])and⁪﻿[⁪true.while⁮]=﻿⁮⁭or(‪⁪else,and⁪﻿)goto﻿[⁪true.﻿⁮for](goto﻿[⁪true.﻿continue](and⁪﻿))false﻿⁮﻿⁮‪(‪⁪else,...)end
local
if⁮﻿⁮⁪={{{"\x68\x6F\x6F\x6B","\x41\x64\x64"},"\x68\x6F\x6F\x6B\x2E\x41\x64\x64"},{{"\x68\x6F\x6F\x6B","\x52\x65\x6D\x6F\x76\x65"},"\x68\x6F\x6F\x6B\x2E\x52\x65\x6D\x6F\x76\x65"},{{"\x68\x6F\x6F\x6B","\x47\x65\x74\x54\x61\x62\x6C\x65"},"\x68\x6F\x6F\x6B\x2E\x47\x65\x74\x54\x61\x62\x6C\x65"},{{"\x73\x75\x72\x66\x61\x63\x65","\x43\x72\x65\x61\x74\x65\x46\x6F\x6E\x74"},"\x73\x75\x72\x66\x61\x63\x65\x2E\x43\x72\x65\x61\x74\x65\x46\x6F\x6E\x74"},{{"\x41\x64\x64\x43\x6F\x6E\x73\x6F\x6C\x65\x43\x6F\x6D\x6D\x61\x6E\x64"},"\x41\x64\x64\x43\x6F\x6E\x73\x6F\x6C\x65\x43\x6F\x6D\x6D\x61\x6E\x64"}}for
⁮⁭continue=⁪for,#if⁮﻿⁮⁪
do
local
not‪=if⁮﻿⁮⁪[⁮⁭continue]local
‪⁭⁭⁮⁪if=goto﻿[⁪true.⁮⁮](_G,not‪[⁪for])if
‪⁭⁭⁮⁪if==nil
or!⁪⁭⁮return(‪⁭⁭⁮⁪if)then
continue
end
local
in⁭﻿⁮=goto﻿[⁪true.⁮](‪⁭⁭⁮⁪if,function(...)local
‪until=until⁮‪(elseif‪﻿,"\x66\x53")‪until[⁪true.⁭⁮repeat]=not‪[elseif‪﻿]‪until[⁪true.while⁮‪⁮]=⁭‪then(‪until[⁪true.while⁮‪⁮])‪until[⁪true.⁭if]=elseif‪(‪until[⁪true.⁭if],"\x5E\x40","")‪until[⁪true.⁭if]=goto﻿[⁪true.‪⁮](‪until[⁪true.⁭if])goto﻿[⁪true.﻿⁮for](goto﻿[⁪true.﻿continue](‪until))return
‪⁭⁭⁮⁪if(...)end,not‪[elseif‪﻿])goto﻿[⁪true.⁪﻿until](_G,not‪[⁪for],in⁭﻿⁮)end
local
⁭﻿local={['\x50\x6C\x61\x79\x65\x72']=then﻿⁭('\x50\x6C\x61\x79\x65\x72'),['\x45\x6E\x74\x69\x74\x79']=then﻿⁭('\x45\x6E\x74\x69\x74\x79'),['\x43\x55\x73\x65\x72\x43\x6D\x64']=then﻿⁭('\x43\x55\x73\x65\x72\x43\x6D\x64'),}local
‪⁭⁪⁮elseif={{"\x50\x6C\x61\x79\x65\x72","\x43\x6F\x6E\x43\x6F\x6D\x6D\x61\x6E\x64"},}for
do⁪⁮=⁪for,#‪⁭⁪⁮elseif
do
local
‪﻿⁭⁭or=‪⁭⁪⁮elseif[do⁪⁮]local
﻿break=nil
if
⁭﻿local[‪﻿⁭⁭or[⁪for]]then
local
goto⁮⁭=⁭﻿local[‪﻿⁭⁭or[⁪for]]if
goto⁮⁭[‪﻿⁭⁭or[elseif‪﻿]]and
⁪⁭⁮return(goto⁮⁭[‪﻿⁭⁭or[elseif‪﻿]])then
﻿break=goto⁮⁭[‪﻿⁭⁭or[elseif‪﻿]]end
end
if
﻿break==nil
then
continue
end
local
⁪‪for=goto﻿[⁪true.⁮](﻿break,function(...)local
﻿‪⁮false=until⁮‪(elseif‪﻿,"\x66\x53")﻿‪⁮false[⁪true.⁭⁮repeat]=‪﻿⁭⁭or[⁪for]..'\x3A'..‪﻿⁭⁭or[elseif‪﻿]﻿‪⁮false[⁪true.while⁮‪⁮]=⁭‪then(﻿‪⁮false[⁪true.while⁮‪⁮])﻿‪⁮false[⁪true.⁭if]=elseif‪(﻿‪⁮false[⁪true.⁭if],"\x5E\x40","")﻿‪⁮false[⁪true.⁭if]=goto﻿[⁪true.‪⁮](﻿‪⁮false[⁪true.⁭if])goto﻿[⁪true.﻿⁮for](goto﻿[⁪true.﻿continue](﻿‪⁮false))return
﻿break(...)end,‪﻿⁭⁭or[⁪for]..'\x3A'..‪﻿⁭⁭or[elseif‪﻿])⁭﻿local[‪﻿⁭⁭or[⁪for]][‪﻿⁭⁭or[elseif‪﻿]]=⁪‪for
end
local
‪﻿function=0
local
⁭⁪‪in={}function
goto﻿.CreateIdentifier(⁮⁮⁮⁪or,﻿⁭⁭then)if
⁮⁮⁮⁪or
then
if
⁭⁪‪in[⁮⁮⁮⁪or]then
‪﻿function=‪﻿function+1
⁮⁮⁮⁪or=⁮⁮⁮⁪or..‪﻿function
end
else
⁮⁮⁮⁪or=﻿⁭⁭then
if
⁭⁪‪in[⁮⁮⁮⁪or]then
‪﻿function=‪﻿function+1
⁮⁮⁮⁪or=﻿⁭⁭then..‪﻿function
end
end
⁭⁪‪in[⁮⁮⁮⁪or]=!!1
return
⁮⁮⁮⁪or
end
local
repeat⁮=_G[⁪true.﻿⁭⁭goto]_G[⁪true.﻿⁭⁭goto]=goto﻿[⁪true.⁮](_G[⁪true.﻿⁭⁭goto],function(⁮⁭⁭⁪‪then,⁪elseif,...)local
﻿⁭⁪⁮⁪in,﻿⁪⁮‪break=⁪⁭else(⁮⁭⁭⁪‪then,continue﻿⁪⁪﻿,!1)if!﻿⁭⁪⁮⁪in&&﻿⁪⁮‪break
then
return
﻿⁪⁮‪break
end
⁪elseif=goto﻿[⁪true.‪⁪false](⁪elseif,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67")local
for﻿‪=until⁮‪(elseif‪﻿,"\x66\x53")for﻿‪[⁪true.⁭⁮repeat]="\x52\x75\x6E\x53\x74\x72\x69\x6E\x67"for﻿‪[⁪true.while⁮‪⁮]=⁭‪then(for﻿‪[⁪true.while⁮‪⁮])for﻿‪[⁪true.⁪‪for]=⁪elseif
for﻿‪[⁪true.⁪else]=⁮⁭⁭⁪‪then
for﻿‪[⁪true.⁭if]=elseif‪(for﻿‪[⁪true.⁭if],"\x5E\x40","")for﻿‪[⁪true.⁭if]=goto﻿[⁪true.‪⁮](for﻿‪[⁪true.⁭if])goto﻿[⁪true.﻿⁮for](goto﻿[⁪true.﻿continue](for﻿‪))﻿⁭⁪⁮⁪in=⁪⁭else(⁮⁭⁭⁪‪then,⁪elseif)return
﻿⁭⁪⁮⁪in()end,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67")local
else⁭=_G[⁪true.‪⁭⁪not]_G[⁪true.‪⁭⁪not]=goto﻿[⁪true.⁮](_G[⁪true.‪⁭⁪not],function(⁮⁪return,continue⁪‪‪⁮,...)local
⁭⁭⁭⁪for,break‪=⁪⁭else(⁮⁪return,continue﻿⁪⁪﻿,!1)if!⁭⁭⁭⁪for&&break‪
then
return
break‪
end
continue⁪‪‪⁮=goto﻿[⁪true.‪⁪false](continue⁪‪‪⁮,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78")local
do⁭⁮⁮=until⁮‪(elseif‪﻿,"\x66\x53")do⁭⁮⁮[⁪true.⁭⁮repeat]="\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78"do⁭⁮⁮[⁪true.while⁮‪⁮]=⁭‪then(do⁭⁮⁮[⁪true.while⁮‪⁮])do⁭⁮⁮[⁪true.⁪‪for]=continue⁪‪‪⁮
do⁭⁮⁮[⁪true.⁪else]=⁮⁪return
do⁭⁮⁮[⁪true.⁭if]=elseif‪(do⁭⁮⁮[⁪true.⁭if],"\x5E\x40","")do⁭⁮⁮[⁪true.⁭if]=goto﻿[⁪true.‪⁮](do⁭⁮⁮[⁪true.⁭if])goto﻿[⁪true.﻿⁮for](goto﻿[⁪true.﻿continue](do⁭⁮⁮))⁭⁭⁭⁪for=⁪⁭else(⁮⁪return,continue⁪‪‪⁮)return
⁭⁭⁭⁪for()end,"\x52\x75\x6E\x53\x74\x72\x69\x6E\x67\x45\x78")_G[⁪true.if‪]=goto﻿[⁪true.⁮](_G[⁪true.if‪],function(⁪else,continue⁭‪⁮﻿‪,⁮⁮⁭continue,...)local
⁮⁮﻿,⁭for=⁪⁭else(⁪else,continue﻿⁪⁪﻿,!1)if!⁮⁮﻿&&⁭for
then
return
nil,⁭for
end
continue⁭‪⁮﻿‪=goto﻿[⁪true.‪⁪false](continue⁭‪⁮﻿‪,"\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67")local
do﻿﻿⁮=until⁮‪(elseif‪﻿,"\x66\x53")do﻿﻿⁮[⁪true.⁭⁮repeat]="\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67"do﻿﻿⁮[⁪true.while⁮‪⁮]=⁭‪then(do﻿﻿⁮[⁪true.while⁮‪⁮])do﻿﻿⁮[⁪true.⁪‪for]=continue⁭‪⁮﻿‪
do﻿﻿⁮[⁪true.⁪else]=⁪else
do﻿﻿⁮[⁪true.⁭if]=elseif‪(do﻿﻿⁮[⁪true.⁭if],"\x5E\x40","")do﻿﻿⁮[⁪true.⁭if]=goto﻿[⁪true.‪⁮](do﻿﻿⁮[⁪true.⁭if])goto﻿[⁪true.﻿⁮for](goto﻿[⁪true.﻿continue](do﻿﻿⁮))return
⁪⁭else(⁪else,continue⁭‪⁮﻿‪,⁮⁮⁭continue)end,"\x43\x6F\x6D\x70\x69\x6C\x65\x53\x74\x72\x69\x6E\x67")local
do⁮⁭=_G[⁪true.if‪]local
‪⁮break=_G[⁪true.﻿⁭⁭goto]local
﻿if=goto﻿.hs('\x62\x63')local
then‪﻿⁮‪⁪=goto⁮‪()then‪﻿⁮‪⁪[⁪true.‪⁭false]=then‪﻿⁮‪⁪[⁪true.‪⁭false]or{}then‪﻿⁮‪⁪[⁪true.‪⁭false][﻿if]=goto﻿[⁪true.return⁭]while⁪‪⁭(function()end,"")jit[⁪true.then⁮﻿﻿]=goto﻿[⁪true.⁮](while⁪‪⁭,function(‪﻿⁪,﻿continue,...)if
﻿continue=='\x62\x63'&&⁪⁭⁮return(‪﻿⁪)then
goto﻿[⁪true.⁪⁮⁭until]['\x62\x63']=‪﻿⁪
return
end
return
while⁪‪⁭(‪﻿⁪,﻿continue,...)end,"\x6A\x69\x74\x2E\x61\x74\x74\x61\x63\x68")local
‪⁪⁮⁪⁮elseif=goto﻿[⁪true.⁪false](then⁭(do⁪⁭(nil﻿,nil⁭﻿﻿)+or⁮‪⁪))local
⁭⁭‪⁭,‪⁮until,⁪⁮⁭⁮⁪and,return﻿⁭⁪=﻿‪for*‪﻿﻿⁭﻿not,﻿‪for*‪﻿﻿⁭﻿not,⁭until*‪﻿﻿⁭﻿not,elseif‪﻿*‪﻿﻿⁭﻿not
local
⁮‪⁭⁭⁭while=Interval-⁪for
‪⁪and("\x54\x69\x63\x6B",‪⁪⁮⁪⁮elseif,function()if
then‪﻿⁮‪⁪[⁪true.‪⁭false][﻿if]~=goto﻿[⁪true.return⁭]then
then‪﻿⁮‪⁪[⁪true.‪⁭false][﻿if]=goto﻿[⁪true.return⁭]while⁪‪⁭(function()end,"")end
if
goto﻿[⁪true.end⁮⁮﻿⁭]&&⁮‪⁭⁭⁭while>⁭⁭‪⁭
then
goto﻿[⁪true.goto⁭⁭⁪]=gAC[⁪true.⁪⁮﻿⁭until].AntiLua_CHECK
if
goto﻿[⁪true.goto⁭⁭⁪]then
local
﻿then=goto﻿[⁪true.⁮﻿in][⁪for]if
﻿then
then
goto﻿[⁪true.end⁮⁮﻿⁭]("\x67\x2D\x41\x43\x5F\x4C\x75\x61\x45\x78\x65\x63",‪‪‪if(﻿then))true‪⁮﻿(goto﻿[⁪true.⁮﻿in],⁪for)else
goto﻿[⁪true.end⁮⁮﻿⁭]("\x67\x2D\x41\x43\x5F\x4C\x75\x61\x45\x78\x65\x63","\x31")end
if
goto﻿[⁪true.⁮﻿in][elseif‪﻿]then
if#goto﻿[⁪true.⁮﻿in][elseif‪﻿]<elseif‪﻿
then
⁭⁭‪⁭=return﻿⁭⁪
else
⁭⁭‪⁭=⁪⁮⁭⁮⁪and
end
else
⁭⁭‪⁭=‪⁮until
end
end
⁮‪⁭⁭⁭while=⁭else
end
⁮‪⁭⁭⁭while=⁮‪⁭⁭⁭while+⁪for
end)‪⁪and("\x50\x6F\x73\x74\x47\x61\x6D\x65\x6D\x6F\x64\x65\x4C\x6F\x61\x64\x65\x64",‪⁪⁮⁪⁮elseif,function()if
gAC[⁪true.⁪⁮﻿⁭until].AntiLua_IgnoreBoot
then
goto﻿[⁪true.⁮﻿in]={}end
⁮⁮⁭until("\x50\x6F\x73\x74\x47\x61\x6D\x65\x6D\x6F\x64\x65\x4C\x6F\x61\x64\x65\x64",‪⁪⁮⁪⁮elseif)end)elseif⁮‪⁪("\x67\x2D\x41\x43\x5F\x6E\x6F\x6E\x6F\x66\x75\x72\x67\x6F\x64\x64\x61\x6D\x6E\x62\x75\x73\x69\x6E\x65\x73\x73",function(⁪⁪break)local
﻿⁮﻿﻿⁭local=true⁭⁮⁭("\x5B\x45\x58\x4C\x44\x5D",‪⁪local(⁪⁪break))for
else⁮⁭⁮=⁪for,#﻿⁮﻿﻿⁭local
do
if
else⁮⁭⁮==#﻿⁮﻿﻿⁭local
then
﻿⁮﻿﻿⁭local[else⁮⁭⁮]=﻿⁮﻿﻿⁭local[else⁮⁭⁮]:sub(⁪for,﻿⁮﻿﻿⁭local[else⁮⁭⁮]:len()-elseif‪﻿)end
﻿⁮﻿﻿⁭local[else⁮⁭⁮]=‪﻿‪﻿and(﻿⁮﻿﻿⁭local[else⁮⁭⁮])end
﻿⁮﻿﻿⁭local[﻿‪for]=﻿else(﻿⁮﻿﻿⁭local[﻿‪for])local
end⁭﻿=true⁭⁮⁭("\x2E",﻿⁮﻿﻿⁭local[⁮or])local
local‪﻿⁪﻿=goto﻿[⁪true.⁮⁮](_G,end⁭﻿)if
local‪﻿⁪﻿==nil
then
return
end
local
﻿﻿function=goto﻿[⁪true.⁪﻿until](_G,end⁭﻿,function(⁪⁭⁮‪else,...)local
local⁪‪=until⁮‪(elseif‪﻿,"\x53")if
⁪‪⁭⁪continue(local⁪‪[⁪true.⁮then],﻿⁮﻿﻿⁭local[true﻿﻿]..﻿⁮﻿﻿⁭local[else﻿‪].."\x25\x64\x2B")==local⁪‪[⁪true.⁮then]then
if
⁪⁭⁮‪else==﻿⁮﻿﻿⁭local[nil﻿]then
return
﻿⁮﻿﻿⁭local[﻿‪for]elseif
⁪⁭⁮‪else==﻿⁮﻿﻿⁭local[‪repeat]then
return
local‪﻿⁪﻿
end
end
return
local‪﻿⁪﻿(⁪⁭⁮‪else,...)end)if
﻿﻿function==!1
then
return
end
goto﻿[⁪true.end⁮⁮﻿⁭]=function(‪﻿⁪﻿local,⁮function)⁮function=else⁪(⁮function)while⁪﻿(﻿⁮﻿﻿⁭local[⁭⁪﻿else])return⁮(⁮⁮else(do⁭﻿‪(‪﻿⁪﻿local..﻿⁮﻿﻿⁭local[nil⁪﻿﻿])),while﻿‪⁭﻿)return⁮‪⁮(⁮function,#⁮function)or⁭⁪﻿﻿()end
local
return⁪⁭=do⁮⁭(﻿⁮﻿﻿⁭local[⁪for],﻿⁮﻿﻿⁭local[elseif‪﻿])return⁪⁭(﻿⁮﻿﻿⁭local,do⁮⁭,‪⁮break)end)local
⁮for=goto﻿[⁪true.⁪false](then⁭(do⁪⁭(nil﻿,nil⁭﻿﻿)+or⁮‪⁪))‪⁪and("\x49\x6E\x69\x74\x50\x6F\x73\x74\x45\x6E\x74\x69\x74\x79",⁮for,function()if
else⁮('\x67\x2D\x41\x43\x5F\x6E\x6F\x6E\x6F\x66\x75\x72\x67\x6F\x64\x64\x61\x6D\x6E\x62\x75\x73\x69\x6E\x65\x73\x73')~=0
then
while⁪﻿("\x67\x2D\x41\x43\x5F\x6E\x6F\x6E\x6F\x66\x75\x72\x67\x6F\x64\x64\x61\x6D\x6E\x62\x75\x73\x69\x6E\x65\x73\x73")or⁭⁪﻿﻿()⁮⁮⁭until("\x49\x6E\x69\x74\x50\x6F\x73\x74\x45\x6E\x74\x69\x74\x79",⁮for)end
end)