local a = {a='JoinTimeGAC',b='Meth_HVH_Threshold',c='gAC_AimbotDetected',d='config'}if!gAC[a.d].ANTI_ANTIAIM
then
return
end
local
b=CurTime
local
c=IsValid
local
d=hook.Add
local
e=math.abs
local
f={["weapon_physgun"]=true,["gmod_tool"]=true,["weapon_physcannon"]=true,["gmod_camera"]=true}d("StartCommand","Bad",function(g,h)if(g:InVehicle()||g[a.c]||!g:Alive()||g:GetObserverMode()!=OBS_MODE_NONE||g:IsBot()||!c(g)||g:IsTimingOut()||g:PacketLoss()>80)then
return
end
if(g[a.a]==nil||!(b()>=g[a.a]+25)||g.PlayerFullyAuthenticated!=true)then
return
end
if
c(g:GetActiveWeapon())&&f[g:GetActiveWeapon():GetClass()]then
return
end
if!g[a.b]then
g[a.b]=0
end
local
i=h:GetViewAngles()local
j,k,l=i.p,i.y,i.r
if
j>180
or
j<-180
or
k>180
or
k<-180
or
l>180
or
l<-180
then
if
g[a.b]>20
then
g[a.c]=true
gAC.AddDetection(g,"Anti-Aim Detected [Code 129]",gAC[a.d].ANTIAIM_PUNISHMENT,gAC[a.d].ANTIAIM_BANTIME)return
else
g[a.b]=g[a.b]+1
end
elseif
g[a.b]>0
then
g[a.b]=g[a.b]-1
end
end)