local
_,a,b,c,d={_="gAC_AimbotDetected",a="gAC_AimbotDetections",b="gAC_MX_AB",c="gAC_MY_AB",d="gAC_View",e="gAC_OldView"},CurTime,IsValid,hook.Add,math.abs
if!gAC.config.ENABLE_CITIZENHACK_CHECKS
then
return
end
local
e={["weapon_physgun"]=!!1,["gmod_tool"]=!!1,["weapon_physcannon"]=!!1,["gmod_camera"]=!!1}c("StartCommand","gAC_AntiCitizen.StartCommand",function(c,f)if
c:InVehicle()||c[_._]||!c:Alive()||c:GetObserverMode()~=OBS_MODE_NONE||c:IsBot()||!b(c)||c:IsTimingOut()||c:PacketLoss()>80
then
return
end
if
c.JoinTimeGAC==nil||!(a()>=c.JoinTimeGAC+25)||c.PlayerFullyAuthenticated~=!!1
then
return
end
if
b(c:GetActiveWeapon())&&e[c:GetActiveWeapon():GetClass()]then
c[_.a]=0
return
end
c[_.b]=d(f:GetMouseX())c[_.c]=d(f:GetMouseY())c[_.d]=f:GetViewAngles()if
c[_.e]==nil
then
c[_.e]=c[_.d]return
end
if
c[_.a]==nil
then
c[_.a]=0
end
if(c[_.b]>0&&c[_.b]<40)||(c[_.c]>0&&c[_.c]<40)then
if
c[_.d]==c[_.e]then
if
c[_.a]>=160
then
c[_._]=!!1
gAC.AddDetection(c,"Anti-citizen detection triggered [Code 109]",gAC.config.CITIZENHACK_PUNISHMENT,gAC.config.CITIZENHACK_PUNSIHMENT_BANTIME)else
c[_.a]=c[_.a]+1
end
elseif
c[_.a]~=0
then
c[_.a]=0
end
elseif
c[_.a]~=0
then
c[_.a]=0
end
c[_.e]=c[_.d]end)